### PR TITLE
MANAGER.DFASL errored when loading -- cl:compile-file(manager) now

### PR DESCRIPTION
**Pull request by masinter**
might have been a git merge artifact? But couldn't load MANAGER without remaking MANAGER.DFASL.

### CODE REVIEW

**Comment by masinter** [comment]
also the compile gave some warnings
image

I wonder how useful it is to save and restore .DATABASE files for individual files, given that it takes 5 minutes (in PR #913 "Add loadup of Masterscope database of the world") to produce a .DATABASE of the entire loadup of FULL plus a few selected additional packages (aka 'fuller').

Should we include MANAGER in 'online' for new users? Or make a default INIT when installing for anyone new to Medley? I'd want to change it from relying on ADVISE though. Needs a new issue tho.

**Comment by rmkaplan** [comment]
LOADDB and DUMPDB are part of DATABASEFNS.  I think that DATABASEFNS redefines LOAD and MAKEFILE to do the database saving and loading implicitly, on a per file basis.  There may be no need to shadow that separately in MANAGER.

**Comment by rmkaplan** [comment]
> 
> I wonder how useful it is to save and restore .DATABASE files for individual files, given that it takes 5 minutes (in PR #913 "Add loadup of Masterscope database of the world") to produce a .DATABASE of the entire loadup of FULL plus a few selected additional packages (aka 'fuller').
> 

This isn't about speed, it's about automating the process of always having up to date MS database as you make incremental changes to files.  Whenever an LFG file is modified and saved, a small database for just that file is created (essentially a third file in the source/compiled/database), and that database is loaded whenever that file is loaded for editing (the databases for all LFG files are loaded by the EDITLFG() function that makes sure you have a complete environment for development.  It guarantees that you also have a complete and up-to-date database for the LFG files, without any further action.

**Review by rmkaplan — APPROVED** [review]
Seems simple enough, maybe tune a little bit more later

**Comment by rmkaplan** [comment]
I merged this, but now I see that there is a glitch:  when the dfasl is loaded, I see a series of messages

"Warning:  The variable Manager.ACTIVEFLG was unknown and has been declared SPECIAL

**Pull request merged**
