### PR TITLE
Another pass on CLOSEALL simplify by calling (OPENP)

### PR DESCRIPTION
**Pull request by masinter**
Perhaps this is better?

### CODE REVIEW

**Comment by nbriggs** [comment]
Seriously bad idea to, for example, close your LAFITE mail folder (which is (OPENP)) while it is being compacted.

**Comment by rmkaplan** [comment]
There seem to be USERVISIBLE, USERCLOSEABLE, and CLOSEALL fields/properties on streams which presumably are supposed to guard against this in some way.  I don’t think they are documented, and I don’t remember them.

But LA.OPENTEMPFILE for example has a (WHENCLOSE STREAM ‘CLOSEALL ’NO) expression.

Maybe CLOSEALL (or maybe CLOSEF) should filter the ones that are not uservisible and userclosable

**Comment by nbriggs** [comment]
`CLOSEALL` used to handle that -- see the differences between the old CLOSEALL and the proposed one.

**Comment by masinter** [comment]
just to be safe, i put the checks back in.

**Comment by masinter** [comment]
Removed all the never-used mentions of \OPENFILES everywhere...

**Review by rmkaplan — APPROVED** [review]
LGTM

**Pull request merged**
