### PR TITLE
Add site-specific init file for emscripten environment

### PR DESCRIPTION
**Pull request by nbriggs**
In preparation for checking in the emscripten/wasm version of maiko.

We need a site-init file that will work well with the limited browser environment.  We need to avoid things that depend on externally set environment variables, and we have control over exactly where in the file-system files will be, so we shouldn't rely on MEDLEYDIR and friends.

Medley files should be placed under `{dsk}<medley>` (we can decide later about pseudo-hosts).  The user's home directory (set up by default by emscripten's packaging) is `/home/web_user`, and the username is always web_user.

This version of the init file does not yet deal with fonts that are not preloaded.

### CODE REVIEW

**Review by masinter — COMMENTED** [review]
The MEDLEYDIR file of utilities including the MEDLEY-INIT-VARS function and variable were set up to allow moving from one environment to another without worrying about the configuration.  If we are going to flush MEDLEYDIR as a function, shouldn't we get rid of the dependencies?
Or else modify MEDLEYDIR to point it to the available file system?

**Comment by nbriggs** [comment]
Umm.... I wish you hadn't force-pushed CLOS into my emscripten branch.
May I force-push it back to what it should be?

I'm not suggesting that we dump MEDLEYDIR and friends for everything, but for the Emscripten environment, it means we have to preload things it depends on, and it's going to set things up that aren't likely to be there.

**Comment by nbriggs** [comment]
(and I believe that the MEDLEYDIR code relies on Unix things that aren't present in the Emscripten environment)

**Comment by masinter** [comment]
I'm sorry about the 'force push'. I think I had the mistaken idea that selecting the "Update via Rebase" operation in the web interface was a good way to see if any conflicts had arisen. Yes of course, you can force-push it back, I trust you'll do that safely. 

On MEDLEYDIR ... I think this PR is OK, but incomplete. It was difficult to get the reinitialization of file system variables that should change when you start a sysout where the local file system has changed, while at the same time preserving user extensions to those variables. ok The problem is probably over-constrained.  The variables are listed in the variable MEDLEY-INIT-VARS and processed by the EVENT function MEDLEY-INIT-VARS.

wouldn't it be simpler to change Maiko to just redefine GETENV("MEDLEYDIR") to return an appropriate value?

**Comment by nbriggs** [comment]
You can try rebasing in your *local* copy, using the git command line interface.  Once a PR has been approved then it will show "This branch has no conflicts with the base branch
Merging can be performed automatically." above the squash/merge button, assuming that is in fact the case.

I've cleaned up, I think - doing the "Update via rebase" can cause trouble for anyone that has checked out the branch and is actively working on it.

**Comment by nbriggs** [comment]
For the WAsm case, I don't think "preserving user extensions to those variables" can be an issue since it's a clean restart from the sysout and the same fixed filesystem every time.   The init file will need to be updated as we add files (like whereis, fonts, lispusers/library/sources) to the emscripten generated file system.  I will look at the list of MEDLEY-INIT-VARS though.

**Comment by nbriggs** [comment]
This is what happens to my branch on my local machine when you rebase:
```
% git status
On branch nhb-add-emscripten-init
Your branch and 'origin/nhb-add-emscripten-init' have diverged,
and have 1 and 40 different commits each, respectively.
  (use "git pull" if you want to integrate the remote branch with yours)

nothing to commit, working tree clean
```
and if one tries a "git pull", it tries to do a merge - which may or may not succeed, depending on the local state.

**Comment by nbriggs** [comment]
And the resulting log history now looks like this:
```
flap% git log
commit 984e29e3f5cb91c6ba0f21fab60877807da87111 (HEAD -> nhb-add-emscripten-init)
Merge: fde9553a 02ad3ab6
Author: Nick Briggs <nicholas.h.briggs@gmail.com>
Date:   Fri Dec 29 10:00:45 2023 -0800

    Merge branch 'nhb-add-emscripten-init' of https://github.com/Interlisp/medley into nhb-add-emscripten-init

commit 02ad3ab61b2365ab2ae4398838b42330b7253c90 (origin/nhb-add-emscripten-init)
Author: Nick Briggs <nicholas.h.briggs@gmail.com>
Date:   Sun Dec 24 21:35:37 2023 -0800

    Add site-specific init file for emscripten environment

commit fde9553af59306215dd350fb5b09ea38654a702f
Author: Nick Briggs <nicholas.h.briggs@gmail.com>
Date:   Sun Dec 24 21:35:37 2023 -0800

    Add site-specific init file for emscripten environment

commit 3727653e2320d30d8fd69e05c5c5f78578ac465d (tag: medley-231217-3727653e, origin/master, origin/HEAD)
```
Since I know I had NOT made any additional changes yet, I switched back to master, deleted my local copy of my branch, and checked out the branch again from github, so now the history looks like
```
flap% git log
commit 02ad3ab61b2365ab2ae4398838b42330b7253c90 (HEAD -> nhb-add-emscripten-init, origin/nhb-add-emscripten-init)
Author: Nick Briggs <nicholas.h.briggs@gmail.com>
Date:   Sun Dec 24 21:35:37 2023 -0800

    Add site-specific init file for emscripten environment

commit 3727653e2320d30d8fd69e05c5c5f78578ac465d (tag: medley-231217-3727653e, origin/master, origin/HEAD, master)
Author: rmkaplan <69548581+rmkaplan@users.noreply.github.com>
Date:   Sun Dec 17 16:42:59 2023 -0800
```
and now I can make additional changes to the init file without having to force-push back to github.

**Comment by nbriggs** [comment]
I've figured out how to make the Emscripten/WebAssmebly runtime provide a MEDLEYDIR environment variable to the WAsm compiled code (no mods to the maiko code), so I am experimenting with pre-packaging the whole necessary file system (128 MB not gzipped) for the MEDLEYDIR-INIT to work.   This PR can remain draft until everything is sorted.

**Comment by masinter** [comment]
I used this (and all other open PRs merged) to test out https://github.com/Interlisp/medley/pull/1479

**Comment by nbriggs** [comment]
Since I made the emscripten build include the whole file system, and figured out a way to make a MEDLEYDIR pointing at it in the emscripten environment, I think we don't need this PR and the branch it references.

@masinter Can you try again without this PR/branch merged?

**Comment by masinter** [comment]
Seems to work fine with medley master too, without this PR.

**Comment by masinter** [comment]
at the 3/4/24 meeting I think we decided to close this as unneeded.

**Pull request closed without merging**
