### PR TITLE
Pull in newer or missing .tedit files

### PR DESCRIPTION
**Pull request by masinter**
- COMPAREDIRECTORIES, COMPARESOURCES, COMPARETEXT, EXAMINEDEFS
- COMPAREDIRECTORIES:  Get AUTHOR only if selected
- EXAMINEDEFS: Better interpretation of TYPE NIL = (FNS FUNCTIONS) with better formatting
- COMPARETEXT: fixed to avoid EOF error if EOL gets confused
- pull in newer or missing tedit files for library

### CODE REVIEW

**Comment by nbriggs** [comment]
Why are we having such a difficult time keeping the PRs to a single topic?  Why not merge the PR associated with the Comparison-cleanups branch and then merge the new PR for the new TEdit files.  They don't overlap so it doesn't matter if they started from different points on the master branch.

**Comment by masinter** [comment]
This doesn't look right. Probably better to redo this.
@rmkaplan let's talk 11/6/23 meeting.

**Comment by rmkaplan** [comment]
> This doesn't look right. Probably better to redo this. @rmkaplan let's talk 11/6/23 meeting.

Yes, I don't know why all these Tedit files got mixed up in this PR, if this was originally the PR about the minor code changes to COMPAREDIRECTORIES etc.

**Comment by masinter** [comment]
ii had the wrong target for a merge. I redid this PR #1398

**Pull request closed without merging**
