### PR TITLE
GITFNS local-origin

### PR DESCRIPTION
**Pull request by rmkaplan**
I hope it's converging

### CODE REVIEW

**Review by masinter — APPROVED** [review]
I fear there will be a long tail of surprises because we're coming in at the "porcelain" level of interface meant for (geeky) humans, rather than tying into the "plumbing" level of the git/github API.
But the github/lisp/file package interactions are interesting at least.

**Comment by rmkaplan** [comment]
Yes, we are sniffing around the edges.  For one thing, the logic for figuring merged and unmerged branches still isn’t right.  How would we get down to the plumbing—direct network access rather than these shell commands?

**Comment by masinter** [comment]
I imagine modern API interfaces aren't more complicated than courier. But I'm not sure the Common Lisp crowd has gotten up to Python or JS -- not sure.

**Comment by nbriggs** [comment]
git just pulls files from the server and puts them onto your local disk, then you look in the files in the .git directory to do what you need to do.

**Comment by nbriggs** [comment]
(using the git plumbing commands to poke around in the files)
Best to have a look at, for example, https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain to see how things work.

**Comment by masinter** [comment]
I think this PR changes to GITFNS(.LCOM) were included with rmk62 a23ce4272

**Pull request closed without merging**
