### PR TITLE
set up list for classifying files without moving them -- for gather-info

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Comment by masinter** [comment]
I've been looking for a way of marking files for sorting out the ones we want to promote, to keep, to move to some other repo, to include in the "everything" masterscope database vs those that are trash etc. The current setup (with lists of files that ere 'OK' per directory (OKLIBRARY OKSOURCES OKLISPUSERS) wasn't good enough. 

There is another PR to make the FULLER.DATABASE and include it in the release (and the dribble files since they're small) .

**Comment by rmkaplan** [comment]
GITFNS indicates that the following files are newer in origin/master than in this PR:

VTCHAT
COMPAREDIRECTORIES
GITFNS

So, if this is merged, will those files move backwards?

**Review by rmkaplan — COMMENTED** [review]
I looked at just the 3 files that github says have changed, not all the other files that GITFNS is reporting.

Github reports a conflict with MEDLEY-UTILS, and GITFNS shows a current (origin/master) version than the one that is in the github compare (4-Aug instead of 17-Jul).  So there is some unscrambling needed. My understanding is that in MEDLEY-UTILS you are just changing the way you register which files should be included in the gather-info.

The changes to LOADUP-FULL and LOADUP-LISP look good.

**Comment by masinter** [comment]
I'm not sure what GITFNS is doing. If you look at what GitHub reports:

image


this PR affects 6 files. There are conflicts with MEDLEY-UTILS that I will have to resolve before the merge will go through.
nothing about VTCHAT  COMPAREDIRECTORIES or GITFNS

**Comment by masinter** [comment]
I'm not sure how to avoid introducing this kind of conflict when trying to "isolate" changes that can be approved and merged independently -- not sure how it happened.

Once the PR is approved by a reviewer, resolving the conflict manually is pretty simple if it's just a matter of pulling the conflicting file from one branch to another.

It should be possible to resolve the conflict ahead of approval..

**Comment by nbriggs** [comment]
Looking at the MEDLEY-UTILS most recently checked into origin/master:
```
% git diff 431d80fb3cd1a6f6a92b00b7d37eaed3326bd948..origin/master -- internal/MEDLEY-UTILS
diff --git a/internal/MEDLEY-UTILS b/internal/MEDLEY-UTILS
index 0e8988d7..0ed86233 100644
--- a/internal/MEDLEY-UTILS
+++ b/internal/MEDLEY-UTILS
@@ -1,25 +1,17 @@
 (DEFINE-FILE-INFO ^^PACKAGE "INTERLISP" ^^READTABLE "XCL" ^^BASE 10)
 
-(FILECREATED "17-Jul-2022 12:44:56" |{DSK}<home>larry>medley>internal>MEDLEY-UTILS.;9| 15959  
+(FILECREATED " 4-Aug-2022 09:50:04" |{DSK}<home>larry>medley>internal>MEDLEY-UTILS.;2| 10212  
 
-      :CHANGES-TO (FNS HCFILES)
+      :CHANGES-TO (VARS MEDLEY-UTILSCOMS)
 
-      :PREVIOUS-DATE "16-Jul-2022 22:08:34" |{DSK}<home>larry>medley>internal>MEDLEY-UTILS.;8|)
+      :PREVIOUS-DATE "17-Jul-2022 12:44:56" |{DSK}<home>larry>medley>internal>MEDLEY-UTILS.;1|)
 
```
It's really not that useful to have a versioned file system at all if the version numbers are going to jump about all over the place even within a single user's files...

**Comment by nbriggs** [comment]
Regarding the files in different states --
```
git merge-base origin/gather-info origin/master
431d80fb3cd1a6f6a92b00b7d37eaed3326bd948
```
so the following files changed on the master branch between the time that the gather-info branch branched from master and now:
```
git diff --name-only 431d80fb3cd1a6f6a92b00b7d37eaed3326bd948 origin/master
internal/COMPTEST
internal/COMPTEST.LCOM
internal/DO-TEST
internal/DO-TEST.LCOM
internal/DO-TEST.TEDIT
internal/DO-TEST.pdf
internal/DTEST.TEDIT
internal/MACROTEST
internal/MACROTEST.LCOM
internal/MACROTESTAUX
internal/MACROTESTAUX.LCOM
internal/MEDLEY-UTILS
internal/MEDLEY-UTILS.LCOM
internal/envos/DSKTEST
internal/envos/DSKTEST.TEDIT
internal/envos/FLOPPYTESTER
internal/envos/RS232TEST
internal/test/filepos/BIG.XCCS
internal/test/filepos/BIGGREEK.UTF8
internal/test/filepos/BIGGREEK.XCCS
internal/test/filepos/FIVE
internal/test/filepos/FPTESTS
internal/test/filepos/GREEK.UTF8
internal/test/filepos/GREEK.XCCS
internal/test/filepos/README
internal/test/filepos/SHORT.XCCS
internal/test/filepos/TFP
internal/test/filepos/TFP.LCOM
internal/test/filepos/ZEROONETWO.XCCS
internal/test/printing/BADFILES.TEST
internal/test/printing/BADFILES.TXT
internal/test/unpackfilename/TESTUPF
internal/test/unpackfilename/TESTUPF.LCOM
internal/test/unpackfilename/TESTUPF.TXT
library/VTCHAT
library/VTCHAT.LCOM
lispusers/COMPAREDIRECTORIES
lispusers/COMPAREDIRECTORIES.LCOM
lispusers/GITFNS
lispusers/GITFNS.LCOM
lispusers/IDLEDEMO
lispusers/PICK
lispusers/PICK.LCOM
lispusers/PICK.TEDIT
sources/INSPECT
sources/INSPECT.LCOM
sources/SEDIT-TOPLEVEL
sources/SEDIT-TOPLEVEL.DFASL
```
and the following files changed on the gather-info branch (and will be merged back into the master branch when the PR is acted on) --
```
% git diff --name-only 431d80fb3cd1a6f6a92b00b7d37eaed3326bd948..origin/gather-info
internal/MEDLEY-UTILS
internal/MEDLEY-UTILS.LCOM
sources/LOADUP-FULL
sources/LOADUP-FULL.LCOM
sources/LOADUP-LISP
sources/LOADUP-LISP.LCOM
```
Since there are files that are common between the two lists, MEDLEY-UTILS and its LCOM, the GITFNS comparison should be squawking about a conflict.  Only the files that are listed as being different between the merge-base and the tip of the gather-info branch are going to be merged when the PR is completed.

**Comment by masinter** [comment]
I redid this PR with the conflict resolved PR #927, so I will close this one.

**Comment by nbriggs** [comment]
You could have used the instructions that github points you at for resolving merge conflicts using the git command line.

**Comment by masinter** [comment]
what i've been doing to run in a system with all the PR's applied is `git checkout master` and then I make a branch (named some variant of `all-prs-merged`  `git checkout -b all-prs-merged`
and then for each PR listed in `gh pr list` doing
`git merge name-of-pr-branch`
when they're all merged, i do a `loadup all` and `loadup db`
this gives me a test environment that I then run in.
i was going from oldest to newest (from the bottom of the `pr list`) But maybe I should go from the top with the idea that they're not approved for so long for a reason, to avoid the situation where an old question will hang up testing newer PRs.

**Pull request closed without merging**
