### PR TITLE
get rid of unused font files from medley release

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Review by rmkaplan — APPROVED** [review]
Seems reasonable.  If we need to retrieve any (like some sizes of Optima?), we can find them under obsolete.

**Comment by masinter** [comment]
i had forgotten this PR when I did them again in the later promote-internal branch

**Comment by masinter** [comment]
oops I messed up; merging this was wrong

**Comment by rmkaplan** [comment]
BTW, there is still a directory fontsold/, is that still relevant?

**Comment by masinter** [comment]
Fonts are still a mess. We need some focus on the "get modern fonts" vs. patching around.

**Pull request merged**
