### PR TITLE
Yet another Logo with parameters for substrings. WINDOW.BITMAP move to Window

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Review by nbriggs — CHANGES_REQUESTED** [review]
This creates `LOGOW.DFASL` without removing `LOGOW.LCOM`.  I don't know which would be preferred (though I'd guess the LCOM), but as it stands it's bad.

**Comment by masinter** [comment]
step toward #1106 #1108 #744 
@fghalasz are you making a SVG version of the logo?
Got rid of .LCOM.

**Comment by nbriggs** [comment]
Is there a reason to choose 2 different font sizes for the two additional strings?
How about:

image

which uses -10 instead of -16 to not reduce the window width so much, and uses TimesRoman 12 BRR for both  the additional strings, and starts the two strings at the same X offset `(+ LMAR 38)`.

**Comment by masinter** [comment]
sure.  Post a PR.
I was hoping I could feed a postscript stream to the drawing program and get out an EPS that I could hand off to Illustrator to turn into a SVG. If only.

**Comment by rmkaplan** [comment]
I like having the same size.  I’d like to see a version with Interlisp and Common Lisp in a san-serif font—might look less busy and more modern.

**Comment by Michele31415** [comment]
On 4/15/2023 2:18 PM, rmkaplan wrote:
> I like having the same size. I’d like to see a version with Interlisp 
> and Common Lisp in a san-serif font—might look less busy and more modern.
I vote for that too.

             - Michele

**Comment by nbriggs** [comment]
I seem to recall a discussion on one of Frank's logo versions about not mixing serif and sans-serif fonts?  But this is what it looks like using Helvetica 12 --

image

Or Optima 14:

image
(I think Helvetica in Medley is better tuned for the screen than Optima, though I like the letter forms in Optima in other circumstances)

**Comment by Michele31415** [comment]
On 4/15/2023 2:40 PM, Nick Briggs wrote:
>
> I seem to recall a discussion on one of Frank's logo versions about 
> not mixing serif and sans-serif fonts? But this is what it looks like 
> using Helvetica 12 --
>
> image 
> <https://user-images.githubusercontent.com/8138841/232247472-984dc25c-2a77-40b6-a320-7531d2b84b73.png>
>
> Or Optima 14:
>
> image 
> <https://user-images.githubusercontent.com/8138841/232247574-9f4a3524-dc24-4f97-b2cb-1f343d499af2.png>
> (I think Helvetica in Medley is better tuned for the screen than 
> Optima, though I like the letter forms in Optima in other circumstances)
>
How about kerning out "Interlisp" to match the width of "Common Lisp"?  
It looks kinda squashed in right now.

Sorta like:

I N T E R L I S P
COMMON  LISP

             - Michele

**Comment by nbriggs** [comment]
Have a look at the code for `LOGOW` and give it a try...

**Comment by fghalasz** [comment]
OK.  I parameterized LOGOW a bit more so that we could easily look at all the options suggested. 

Once we settle on the details (see choices below), I can whip out a SVG version of our FINAL choice. 

Here are the various Tweaks on Larry's original that have been suggested so far (with a bit of clean-up added in some cases) plus some possible tweaks (e.g., all text in helvetica):

# Option 0:  Larry's latest (image, then parameters used to create image)
Option0
Option0 Params

# Option 1:  Larry's latest, cleaned-up a bit (centered, etc.)
Option1
Option1 Params

# Option 2:   Nick's equal font sizes
Option2
Option2 Params

# Option 3:   Nick's equal font sizes, cleaned-up a bit (centered, etc.)
Option3
Option3 Params

# Option 4:  Ron's suggestion to use Sans Serif for the subtext
Option4
Option4 Params

# Option 5:  Adding Michelle's suggestion to kern "Interlisp" (using stupidly simple kerning that adds space without paying attention to the surrounding characters) using Helvetica subtext
Option5
Option5 Params

# Option 6:  Adding Michelle's suggestion to kern "Interlisp"  - with TimesRoman subtext
Option6
Option6 Params

# Option 7:  All text helvetica; main text kerned a bit (helvetica too squished), subtext not kerned.
Option7
Option7 Params

**Comment by Michele31415** [comment]
On 4/16/2023 6:49 PM, Frank Halasz wrote:
>
> OK. I parameterized LOGOW a bit more so that we could easily look at 
> all the options suggested.
>
> Once we settle on the details (see choices below), I can whip out a 
> SVG version of our FINAL choice.
>
Thank you Frank for doing the work.  My vote is for option 5.  Using 
Helvetica subtext helps emphasize the overall name "Medley".  The 
kerning looks OK to me and it balances out the two subtexts.  Just IMHO.

             - Michele

**Comment by fghalasz** [comment]
Two more logo tweaks.  Helvetica seems to have some kerning issues - chars are squished together, at least in bold.  So added some kerning to all helvetica strings in the logos with helvetica.

# Option 8:  Option 4 with extra kerning in substrings
Option8
Option8 Params

# Option 9:  Option 7 with extra kerning in substrings
Option9

**Comment by fghalasz** [comment]
FWIW, my votes:  

Top choice:  Option 9 (~Option 7) 
Second choice: Option 8 (~Option 4).

Unlike Michelle, I am not thrilled about the kerned "Interlisp" variations.

**Comment by pamoroso** [comment]
I like options 8 and 4.

**Comment by rmkaplan** [comment]
I also like 8 and 4

**Comment by masinter** [comment]
I like 8 better than 4. Ship it.

**Comment by fghalasz** [comment]
Ok. Moved LOGOW to Option 8.  Also added some top and right margins to the default placement of LOGOW on the screen to avoid it looking so squished into the upper right corner.  

Did not all Makesys Name to the upper-right corner of the LOGOW since it just didn't look right.  Probably should add the Makesys Name (e.g., Full, Apps, Lisp, Online, etc) to the WHO-LINE if we need it to be visible at all times.

**Comment by nbriggs** [comment]
@fghalasz - I don't think we need the makesysname to be visible at all times.

**Review by fghalasz — APPROVED** [review]
Ok.  Ready to go.

**Review by nbriggs — APPROVED** [review]
LGTM.

**Pull request merged**
