### PR TITLE
Release tweaks

### PR DESCRIPTION
**Pull request by masinter**
wasn't subsumed by #447 after all

### CODE REVIEW

**Comment by masinter** [comment]
it's hard to track what changes are in which branch. But this one edited different files than #447  even though they both have 'release' in their title.

**Comment by nbriggs** [comment]
I'll review this before the end of the day.

**Review by nbriggs — APPROVED** [review]
LGTM.

**Comment by nbriggs** [comment]
It would be good though if the commit comments explained more of the reasoning behind the changes (e.g., MSRECORDTRANFLG should not be set to T because... and DFNFLG should be PROP because... when loading system code it is dangerous to replace compiled definitions with interpreted ones).

**Pull request merged**
