### PR TITLE
Tedit3 refactor tedit.build.pctb

### PR DESCRIPTION
**Pull request by rmkaplan**
Put this out so Larry can see how I have divided things up, in a first of probably several steps.

### CODE REVIEW

**Comment by nbriggs** [comment]
You don’t need to make a PR if you just want someone to look at a branch that isn’t complete.

**Comment by rmkaplan** [comment]
OK.  But this is going to be a long incremental path, and I think intermediate stages are worth incorporating.

**Review by masinter — APPROVED** [review]
running with this merged

**Comment by masinter** [comment]
not sure what's going on with conflicts
This is the 3-way comparison case.

**Comment by rmkaplan** [comment]
I don't understand why there is a conflict.  I know what the correct version of TEDIT-FILE should be.  I'm not sure how to get it into the right place

**Comment by nbriggs** [comment]
The version of TEDIT-FILE that's currently on master is presumably different from the version of TEDIT-FILE that you started from for the TEDIT3-Refactor-TEDIT.BUILD.PCTB branch -- since they have diverged git can't cope.\

Is the version on TEDIT3-Refactor-TEDIT.BUILD.PCTB the correct one?   If so, I can resolve the conflict and push it back to the TEDIT3-Refactor-TEDIT.BUILD.PCTB branch.

**Comment by rmkaplan** [comment]
I think so.  If not, I can make a new one on top, once this is resolved.

**Comment by nbriggs** [comment]
I think it's ready to merge now, but someone (Ron?) should check the contents carefully with PRC to make sure it's good.

**Comment by rmkaplan** [comment]
I think now I will try to update the slightly newer version to the TEdit3 branch

**Comment by rmkaplan** [comment]
Oops, no, I think it’s good.

**Pull request merged**
