### PR TITLE
Second recompile fdev #457

### PR DESCRIPTION
**Pull request by rmkaplan**
I hope this is better, just the compiled files.  I also included the fix to FONTPROFILE to regularize the COMMENTFONT in the NS profile, and eliminated a very old FONTPROFILEPATCH that duplicated FONTPROFILE.

Note: the files CLSTREAM and LLDISPLAY have FUNCTIONS, and they had a FILETYPE property of CL:COMPILE-FILE.  But the compiled files were LCOM's instead of DFASL's, and the functions were actually not compiled.  I compiled them with FAKE-COMPILE-FILE that compiles everything but produces LCOMs to match what was there.  Maybe we need to sweep to find files with LCOMs that don't have the right FILETYPE.

### CODE REVIEW

**Review by nbriggs — CHANGES_REQUESTED** [review]
This looks much better.  I notice, though, that the font set BIGGERNS has a similar problem to the font set NS that you fixed here.  No MENUFONT 5 or COMMENTFONT 6.

Perhaps just add another commit of the fixed source & LCOM for FONTPROFILE to the existing branch...  OR we could leave it until after this is merged.

**Comment by rmkaplan** [comment]
I committed a new FONTPROFILE.

But also note that something else is a little off, even in STANDARD.  The profiles assign the same number but different actual fonts to DEFAULTFONT and ITALICFONT.  It may be that ITALICFONT is not used by PRETTYDEF but is referenced directly in other contexts, so that the number doesn’t matter.  But it still odd.

**Comment by masinter** [comment]
on my wish list is a way to set "higher resolution" fonts, especially for who-line and the lispx event numbers.

FONTSET isn't right

**Review by masinter — APPROVED** [review]
was FONTPROFILEPATCH deleted but not the .LCOM?

**Comment by rmkaplan** [comment]
I don’t have it anymore, it might have been missed on the first commit and then done on a follow-on.

**Comment by nbriggs** [comment]
FONTPROFILEPATCH.LCOM is gone, as it should be:

```
commit 74ea166c38bd5156ac886fab8ab8c1da06f87509
Author: rmkaplan <ron.kaplan@post.harvard.edu>
Date:   Mon Sep 6 15:58:22 2021 -0700

    FONTPROFILE:  Fix NS COMMENTFONT, delete FONTPROFILEPATCH
    
    This reverts commit 2615140ede9117b722f555e6603029f20274dd0e.

:100644 100644 106d0d0... 2cd849a... M  sources/FONTPROFILE
:100644 100644 a58f35d... f1435c5... M  sources/FONTPROFILE.LCOM
:100644 000000 04db1fc... 0000000... D  sources/FONTPROFILEPATCH
:100644 000000 df5b655... 0000000... D  sources/FONTPROFILEPATCH.LCOM
```

**Review by nbriggs — APPROVED** [review]
Looks good now.

**Pull request merged**
