### PR TITLE
Changes to interpret.rem.cm and sysout et all

### LINKED ISSUE #227: SYSOUT returns wrong value when resuming
**Describe the bug**
SYSOUT seems to return a (non LISTP) non-existant version when resuming

**To Reproduce**
make a sysout. LOGOUT and restart it
The SYSOUT call returns the name of a new (non-existent) version

**Expected behavior**
return a list of the name of the restarted version

**Screenshots**
image

image

### PR DESCRIPTION
**Pull request by masinter**
this fixes the problem of leaving init file open.
While I was there, I went through and fixed #227 , 2017 patches to ADIR weren't correct

### CODE REVIEW

**Comment by nbriggs** [comment]
Also closes #267

**Review by nbriggs — APPROVED** [review]
LGTM

**Comment by rmkaplan** [comment]
I made a new tmp/full from scratch, and the init files are now no longer open when it starts up.

However, I now get a stream-not-open error when I run the LFG loader as a greetfile, in the standard way.  The sysout does seem to be constructed before the error happens.  

Also:  it appears that the retrofitting changes to ADIR undid the intended effect of the previous patches, which was to make version-numbered sysouts and makesys's.  Now it seems like the new sysouts smash on top of the previous one.  \COPYSYS doesn't do version numbering, which is why the patch was to make the sysout under a tmp name and then rename it.

**Comment by masinter** [comment]
\COPYSYS is a terrible mess.  A clue is its location (MOD44IO). It's a good idea to remove all the complexity of sysout to non-maiko-{DSK}.

**Pull request merged**
