### PR TITLE
Added IBM-EGA fixed pitch font files

### PR DESCRIPTION
**Pull request by MattHeffron**

### CODE REVIEW

**Comment by nbriggs** [comment]
If you want to access these with, for example `(FONTCREATE 'IBM-US 14 'MRR 0)` then the file `ibm-us14.strike` should be named `IBM-US14-MRR-C0.DISPLAYFONT` and so on for the others.

**Comment by masinter** [comment]
I intended just to fix Matt's PR but wound up picking up some other commits for reasons I don't understand. Help

**Review by nbriggs — COMMENTED** [review]
How did this PR/branch pick up all the other changes?

**Comment by nbriggs** [comment]
He's asking for a merge from his fork, so you shouldn't be able to write back into it.   What did you do?

**Comment by masinter** [comment]
reconstructing from history...
``
gh pr list
gh pr checkout 868
git checkout larry-work
```
various messing about
```
git branch -a
git checkout IBM-EGA-fonts

git whatchanged fonts
cd fonts/displayfonts/c0
git mv ibm14.strike IBM14-MRR-C0.DISPLAYFONT
```
.... more git mv's
```
git commit -m "move to names that will be recognized"
git push

```

**Comment by nbriggs** [comment]
What does your .git/config look like?  I don’t know what “gh pr checkout 868” would have done to your "git status”.   I don’t ever use “gh” (can’t on one machine, won’t on the other).

**Comment by masinter** [comment]
superseded by #882 
Ron may need to change GITFNS to not bomb

**Pull request closed without merging**
