### PR TITLE
This fixes GITFNS prc not showing any changed files with certain filename/path patterns.

### PR DESCRIPTION
**Pull request by MattHeffron**
This fixes GITFNS `prc` not showing any changed files if they included `.git` in the full name.
It now is specific, and excludes only those in the `.git/` top-level directory.
GITFNS also ignored changed files at the top-level of the repo. This is fixed also.
This can be tested with PR #1756

### CODE REVIEW

**Comment by rmkaplan** [comment]
When I run prc and click on this pr in the menu, I get an "unknown branch origin/mth17... error.

**Comment by rmkaplan** [comment]
Actually, maybe in the wrong version.  Let me check...

**Comment by rmkaplan** [comment]
OK, it works for prc on the test pr 1756, but does give the "unknown branch" error on 1757.  Error is inside GIT-BRANCH-EXISTS?

**Comment by MattHeffron** [comment]
@rmkaplan It turns out that .git in the branch name caused the same issue of the branch unseen.
I believe that this version is correct, but I may have missed some cases where it should have allowed .git in a branch name, or allowed .git where it shouldn't have.

**Review by rmkaplan — APPROVED** [review]
Mostly just passing the ALL flag, plus specifing top-level .*.  LGTM

**Pull request merged**
