### PR TITLE
reset HOME during loadups to avoid (GREET)

### PR DESCRIPTION
**Pull request by masinter**
MAKESYS differs from SYSOUT in insisting that a GREET comes after, with an empty history

Scripts that start with using the LDEINIT to set a different site greeting are subject to finding the user's GREET file anyway.  While this logic is bonkers, the simplest fix is just to set HOME to /dev/null when running a loadup that starts with a MAKESYS'd image ....

### CODE REVIEW

**Review by rmkaplan — CHANGES_REQUESTED** [review]
This didn't seem to make a difference, I did a loadup with these scripts and at the end when I started the new full with -nogreet I found that my personal INIT had still been loaded

**Comment by masinter** [comment]
> This didn't seem to make a difference, I did a loadup with these scripts and at the end when I started the new full with -nogreet I found that my personal INIT had still been loaded

That is a different problem -- "run-medley -nogreet still greets #462 "
 This one cures the "loadup" problem (I think)

**Comment by rmkaplan** [comment]
Well, how can I determine whether that’s the case?

When I start up a new full.sysout, it doesn’t show that it is loading any of the files that my INIT brings in.  But those files are there.

**Comment by masinter** [comment]
for reasons i can't remember (but I could make up some), some of the GREET files are loaded SYSLOAD (no printing, smash filecoms)

**Comment by rmkaplan** [comment]
My init file is loaded when LOADUP-FULL.CM is loaded

**Comment by masinter** [comment]
Anyway: this PR fixes an immediate problem that loadups done by anyone with an INIT in their home directory will be polluted.
(That's not me -- I had a ~/init.lcom which was a symbolic link to my dropbox ilisp directory -- but I got rid of that and just LOAD the "greet" file LARRY from there. 

I have an idea for run-medley -nogreet that I'll post to #462

**Comment by masinter** [comment]
it would be nice if the result would run with starter.sysout and the venuesysouts. So requiring a new version of GREET would make trouble.

What if -nogreet set LDEINIT to   medley/greetfiles/nogreet  
and set up nogreet to (P (AND (STKPOS 'GREET) (RETFROM 'GREET)))
(need to close the 'nogreet' input stream)

I'm guessing the use case for -nogreet is to do manual loadups ? It was added not so long ago.

**Comment by masinter** [comment]
```
larry@TV-PC:~/medley$ git status
On branch no-greet-loadup
Your branch is up to date with 'origin/no-greet-loadup'.

nothing to commit, working tree clean
larry@TV-PC:~/medley$ git pull
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 27 (delta 26), reused 22 (delta 22), pack-reused 0
Unpacking objects: 100% (27/27), 28.95 KiB | 511.00 KiB/s, done.
From https://github.com/Interlisp/medley
   95c9496..b760d00  master     -> origin/master
Already up to date.
larry@TV-PC:~/medley$ git status ^C
larry@TV-PC:~/medley$ clear
larry@TV-PC:~/medley$ git status
On branch no-greet-loadup
Your branch is up to date with 'origin/no-greet-loadup'.

nothing to commit, working tree clean
larry@TV-PC:~/medley$ git pull
Already up to date.
larry@TV-PC:~/medley$ time ./scripts/load
loadup-all.sh             loadup-aux.sh             loadup-full.sh            loadup-lisp-from-mid.sh
loadup-and-release.sh     loadup-full-from-lisp.sh  loadup-init.sh            loadup-mid-from-init.sh
larry@TV-PC:~/medley$ time ./scripts/loadup-all.sh
running: lde -g 1042x790 -sc 1024x768 -m 256  loadups/starter.sysout
greet: /home/larry/medley/sources/LOADUP-INIT.LISP
---- made ----
-rw-r--r-- 1 larry larry   89325 Sep  7 14:29 tmp/I-NEW
-rw-r--r-- 1 larry larry   70757 Sep  7 14:29 tmp/I-NEW.LCOM
-rw-r--r-- 1 larry larry 4313088 Sep  7 14:29 tmp/init.dlinit
-rw-r--r-- 1 larry larry  116205 Sep  7 14:29 tmp/init.dribble
-rw-r--r-- 1 larry larry 4166656 Sep  7 14:29 tmp/init.sysout
-rw-r--r-- 1 larry larry   55809 Sep  7 14:29 tmp/RDSYS
-rw-r--r-- 1 larry larry   42977 Sep  7 14:29 tmp/RDSYS.LCOM
--------------
running: ldeinit -g 1042x790 -sc 1024x768 -m 256  tmp/init.dlinit
greet: /home/larry/medley/sources/XREM.CM
Failed to find UNIXCOMM file handles; no processes
MAKEINIT.EXPRESSIONSSNSSSsions:SIONS
---- made ----
-rw-r--r-- 1 larry larry 4971520 Sep  7 14:29 tmp/init-mid.sysout
--------------
running: lde -g 1042x790 -sc 1024x768 -m 256  tmp/init-mid.sysout
greet: /home/larry/medley/sources/LOADUP-LISP.CM
---- made ----
-rw-r--r-- 1 larry larry   30042 Sep  7 14:29 tmp/lisp.dribble
-rw-r--r-- 1 larry larry 8521728 Sep  7 14:29 tmp/lisp.sysout
--------------
running: lde -g 1042x790 -sc 1024x768 -m 256  /home/larry/medley/tmp/lisp.sysout
greet: /home/larry/medley/sources/LOADUP-FULL.CM
---- made ----
-rw-r--r-- 1 larry larry     8747 Sep  7 14:29 tmp/full.dribble
-rw-r--r-- 1 larry larry 10460160 Sep  7 14:29 tmp/full.sysout
--------------
running: lde -g 1042x790 -sc 1024x768 -m 256  tmp/full.sysout
greet: /home/larry/medley/tmp/loadup-aux.cm
---- made ----
-rw-r--r-- 1 larry larry  173292 Sep  7 14:29 tmp/exports.all
-rw-r--r-- 1 larry larry 2335687 Sep  7 14:29 tmp/whereis.hash
--------------
**** DONE ****

real    0m38.403s
user    0m31.959s
sys     0m6.031s
larry@TV-PC:~/medley$ ./scripts/copy-all.sh
larry@TV-PC:~/medley$ ./run-medley -nogreet -full
running: lde -g 1440x900 -sc 1440x900 -m 256  /home/larry/medley/loadups/full.sysout
greet: /home/larry/medley/greetfiles/NOGREET
```
and in the resulting Lisp window
image

**Review by nbriggs — CHANGES_REQUESTED** [review]
There's a pile of stuff that doesn't look as though it should be here...

**Comment by nbriggs** [comment]
I think you should aim to `git rebase master` in these "topic" branches that were forked from master in order to get them up-to-date for testing...

**Comment by masinter** [comment]
> I think you should aim to `git rebase master` in these "topic" branches that were forked from master in order to get them up-to-date for testing...

following
https://stackoverflow.com/questions/3876977/update-git-branches-from-master/28505516

I tried 
```
git fetch 
git rebase origin/master
```
to no good effect
```
larry@TV-PC:~/medley$ git fetch
larry@TV-PC:~/medley$ git rebase origin/master
Successfully rebased and updated refs/heads/no-greet-loadup.
larry@TV-PC:~/medley$ ls internal/library/MAK
MAKE-EXPORTS-ALL       MAKE-PS                MAKE-PS.LCOM           MAKE-TCP-EXPORTS       MAKE-TCP-EXPORTS.LCOM
larry@TV-PC:~/medley$ ls internal/library/MAKE-P^C
larry@TV-PC:~/medley$ git push
To https://github.com/Interlisp/medley.git
 ! [rejected]        no-greet-loadup -> no-greet-loadup (non-fast-forward)
error: failed to push some refs to 'https://github.com/Interlisp/medley.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
larry@TV-PC:~/medley$ git pull
fatal: Not possible to fast-forward, aborting.
larry@TV-PC:~/medley$ git pull --rebase
Successfully rebased and updated refs/heads/no-greet-loadup.
larry@TV-PC:~/medley$ git push
Enumerating objects: 143, done.
Counting objects: 100% (143/143), done.
Delta compression using up to 8 threads
Compressing objects: 100% (90/90), done.
Writing objects: 100% (91/91), 108.99 KiB | 2.42 MiB/s, done.
Total 91 (delta 75), reused 4 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (75/75), completed with 49 local objects.
To https://github.com/Interlisp/medley.git
   462aa70..9a377dd  no-greet-loadup -> no-greet-loadup
```

**Comment by masinter** [comment]
I'm guessing @rmkaplan has LOGINDIR set and seting HOME wasn't enough.

Anyway, closing this branch in favor of #464

**Comment by rmkaplan** [comment]
Yes, I have LOGINDIR set to "{DSK}$HOME/lisp"

**Pull request closed without merging**
