### PR TITLE
assume process streams are UTF-8

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Review by rmkaplan — APPROVED** [review]
CLIPBOARD asserts its own externalformat on its process stream,also  currently UTF-8.  Maybe that now is needless confusion, that that is not a source of variability above and beyond what all process streams do?

**Comment by nbriggs** [comment]
A process stream is only UTF-8 if the LANG family of environment variables says so.  It's not correct to blindly assert so.

**Comment by rmkaplan** [comment]
Seems like UNIXCOMM should read the UNIX-GETENV and set the external format, that CLIPBOARD should then leave it alone.

Note:  If you are moving UNIXCOMM to sources, delete it from library.

**Comment by nbriggs** [comment]
It’s not a fundamental part of the system, I think it should stay in library… ?

**Comment by masinter** [comment]
it wasn't my intention to move UNIXCOMM, I'll add a check for the LANG environment variable and use it to determine the external format/ charset encoding (this perhaps should be a maiko GETPARM subrcall value but that's another story).

**Pull request merged**
