### PR TITLE
hash p write pathname

### PR DESCRIPTION
**Pull request by masinter**
- **#P"pathname" reads in as pathname**
- **#P"pathname" used for printing pathnames**
do reading first

### CODE REVIEW

**Comment by masinter** [comment]
I closed #1611 since it was included in this PR, and you will need both. This isn't changing the implementation, just adding the #P reader macro.

**Comment by nbriggs** [comment]
Presumably this doesn't affect reading the old `#.(PATHNAME "foo")`, since `#.` is just an eval reader macro and `(PATHNAME "foo")` is a normal way to create a pathname.  There are a bunch of references to `#.(PATHNAME ...)` in the envos repository, though there are none that I can see in Medley or Notecards.

**Comment by masinter** [comment]
If there were any #.(PATHNAME "string") around, they would read in no problem.

**Review by nbriggs — CHANGES_REQUESTED** [review]
I believe loading this file 'ALLPROP and remaking it would fix the duplicate COMS issue.

**Comment by masinter** [comment]
The duplication of CMLPATHNAMESCOMS in this case is a leftover from Interlisp-10, where the compiled code for calling a lambda-nospread function (LAMBDA N ... (ARG N 1) ...) was different than calling a spread. It is still needed for NLAMBDA's.

**Comment by nbriggs** [comment]
OK, but I don't understand how having the exact same RPAQQ to set the CMLPATHNAMECOMS twice in different places in the file affects how lambda no-spread and nlambdas are compiled.  Can you enlighten me?

**Comment by nbriggs** [comment]
And this was a newly introduced change - it was apparently OK before the addition of `#P pathname`, but something about that caused it to be added?

**Review by nbriggs — APPROVED** [review]
LGTM.

**Pull request merged**
