### PR TITLE
Add even.if.visible parameter to TEDIT.NORMALIZECARET

### PR DESCRIPTION
**Pull request by fghalasz**
Add even.if.visible parameter to TEDIT.NORMALIZECARET that sets caret to top line even if its already visible in the panel. 

For Notecards.

### CODE REVIEW

**Review by rmkaplan — COMMENTED** [review]
This looks good, but depends on 4th round.

I can move that one file into 4th round, and then should this be deleted/closed?

**Comment by masinter** [comment]
4th round can be merged after cpv is fixed

**Comment by fghalasz** [comment]
@rmkaplan   Note that this is a pull request to merge my change into your Tedit-4th-round branch - not into master.   If you merge this pull request into Tedit-4th-round, it will merge into master whenever you merge Tedit-4t-round.

**Comment by fghalasz** [comment]
@rmkaplan.  Ooops.  I see that you already "manually merged" the change into Tedit-4th-round.  So I will delete this PR and branch.

**Comment by fghalasz** [comment]
Closed as already done "manually"

**Pull request closed without merging**
