### PR TITLE
SPY.POINTERS is always T (no 2-byte atoms)

### PR DESCRIPTION
**Pull request by masinter**
spy-no-background redone:
* SPY.POINTERS is always T (no 2-byte atoms)
* SPY uses special \BACKGROUND to skip sammpling both \BACKGROUND-YIELD (calls to YIELD subr), or any sample under the background functdion if \BACKGROUND.PROCESS is non-NIL (the default)

### CODE REVIEW

**Comment by masinter** [comment]
I pushed more changes after Approval -- please re-review

**Comment by rmkaplan** [comment]
Is BACKGROUNDE a typo?

**Comment by masinter** [comment]
\BACKGROUNDE was a typo. I wound up changing the name of the variable to \IGNORE.BACKGROUND to be different from the function name \PROCESS.BACKGROUND. Testing this, \IGNORE.BACKGROUND NIL shows warped results

**Comment by rmkaplan** [comment]
So, still more work to do?

**Pull request merged**
