### PR TITLE
Add support for cl: loop for hash tables

### PR DESCRIPTION
**Pull request by masinter**
Adds to XCL-LOOP an addition for supporting iterating through a hash file.
Not a direct port, had some ANSI . CLtL2 updates (declare (ignorable --))
includes TEST-HASH-LOOP()

### CODE REVIEW

**Comment by masinter** [comment]
This PR now includes a fix to the problem of the LOOP macro not processing 'repeat N' clauses (bug in loop:repeat-clause). This bug was in the original from SACL.

**Review by nbriggs — COMMENTED** [review]
I made a new full.sysout on this branch, and when I ran (TEST-HASH-LOOP) it dropped into URaid, having picked up a bad array block pointer during a GC.

```
    frame #6: 0x000000010bf9394e ldex`panicuraid(sig=11, info=<unavailable>, context=<unavailable>) at timer.c:795:3 [opt]
    frame #7: 0x00007ff800c72dfd libsystem_platform.dylib`_sigtramp + 29
    frame #8: 0x000000010bfb0883 ldex`reclaimarrayblock(ptr=208535552) at gcfinal.c:481:37 [opt]
    frame #9: 0x000000010bfb0afd ldex`gcreccell(cell=<unavailable>) at gcrcell.c:189:28 [opt]
    frame #10: 0x000000010bfb1d5c ldex`gcmapscan at gcmain3.c:131:7 [opt]
    frame #11: 0x000000010bfb2553 ldex`dogc01 at gcr.c:113:3 [opt]
    frame #12: 0x000000010bfb25de ldex`doreclaim at gcr.c:128:5 [opt]
    frame #13: 0x000000010bf91117 ldex`OP_subrcall(subr_no=<unavailable>, argnum=<unavailable>) at subr.c:427:7 [opt]
    frame #14: 0x000000010bf84d22 ldex`dispatch at xc.c:683:7 [opt]
    frame #15: 0x000000010bf9da89 ldex`start_lisp at main.c:749:3 [opt]
    frame #16: 0x000000010bf9d7f8 ldex`main(argc=<unavailable>, argv=0x00007ff7b3f8e788) at main.c:696:3 [opt]
    frame #17: 0x00000001110bf52e dyld`start + 462
```

**Comment by masinter** [comment]
i'm baffled -- I can't reproduce the problem. The added code for the hash iterator doesn't acdtually write any storage (no PUTBASE anything) ... it's pretty much the algorithm in MAPHASH with stack based variables turned into compiled closures. ..

By any chance, are you running with maiko compiled with some kind of stack and/or freelist checking turned on?

**Comment by nbriggs** [comment]
I deleted the sysouts and the maiko executables and emade everything from scratch, and now it appears to be working.  I didn't change any maiko configuration/code.  I don't know what was going on - but if you don't see the problem, and I am no longer seeing the problem, and there's nothing about the code that is suspicious, then I think it's probably better to merge it and press on.

**Review by nbriggs — APPROVED** [review]
OK.  Wondering how it ended up with an LCOM originally, since it has COMPILE-FILE as the compiler type, but I see the LCOM is being replaced by a DFASL.

**Pull request merged**
