### PR TITLE
fix #411 scanfilehelp suggested 1100support

### LINKED ISSUE #411: error message 'call 1100support' doesn't give phone number
image

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Comment by rmkaplan** [comment]
Looking at this again, why does it call HELP instead of causing an error?

What could the user do in this situation?

**Comment by masinter** [comment]
it's kind of crazy -- but not really worth fixing.
On modern machines just ignore the filemap or fix it.
I wouldn't mind marking #411 as "won't fix".

**Review by rmkaplan — APPROVED** [review]

**Comment by rmkaplan** [comment]
This is still  a draft.  Can we incorporate this one way or another, and get rid of this?

**Comment by masinter** [comment]
I think this was  harmless and probably shouldn't have been an issue, but ...

**Pull request merged**
