### PR TITLE
Move pick to lispusers

### PR DESCRIPTION
**Pull request by masinter**
add PICK from MEDLEY-UTILS into independent LispUsers

### CODE REVIEW

**Review by rmkaplan — COMMENTED** [review]
I don't understand the pick tedit file.  Can you give a few examples?

**Comment by masinter** [comment]
I added lots of examples.
I changed it to also pick other projects, directories....

**Review by rmkaplan — APPROVED** [review]
A few typos in the pick.tedit file, otherwise good.  I'll approve, spelling correction is optional

**Comment by masinter** [comment]
I blame the typos on being unable to see the tiny characters even with high magnification reading glasses. We need bigger screen fonts.

**Pull request merged**
