### PR TITLE
Rmk79  tedit 3rd round

### PR DESCRIPTION
**Pull request by rmkaplan**
This is the next generation of reworks and rewrites.  Still draft, report issues in screen highlighting, caret location, any odd behavior.  Subwindows may not behave properly.

Plus some new features:

Meta-A/a:  Select all  (was in Modernize)
M-G/g: Find again
M-N/n: Go to next >>xx<< field
M-p/P:  Bring up the hardcopy menu
M-R/r:  Redo last action on a new selection
M-S/s:  Substitute in current selection
M-u/z: Sequential undos
M-U/Z: Sequential undo of undos

### CODE REVIEW

**Comment by rmkaplan** [comment]
Another commit adds backward search (with wild cards):
   M-f:  forward search
   M-F: backward search
   M-g: forward search again
   M-G: backward search again

**Comment by rmkaplan** [comment]
I'm removing the draft status since this has been pretty solid through lots of my testing and use, including complicated LFG applications.  Other patterns of use may reveal other glitches (including a few from the original code that have been too sporadic to trap). I now encourage loading up trying it out.

**Comment by masinter** [comment]
this PR has conflicts with PDFSTREAM that I'm not sure how to untagle.
I really wish the keystroke changes were part of a larger modernization of tedit key bindings rather than mixed in with this very large rewrite.

**Comment by rmkaplan** [comment]
This PR should be deleted, replaced by 4th round.

**Comment by rmkaplan** [comment]
And actually, in 4th round I am still working on an inherited problem with window splitting that has shown up in more testing.

But thanks for dealing with these simple PRs, keeping consistent over long time periods has been a real problem.

(But still, high priority:  macros in masterscope.  Without that I’m beginning to grind to a halt.)

**Pull request closed without merging**
