### PR TITLE
Rmk47: TEDIT, GITFNS, COREIO

### PR DESCRIPTION
**Pull request by rmkaplan**

### CODE REVIEW

**Comment by rmkaplan** [comment]
This is when you are clicking on an item in the comparesources window?  (But you aren’t getting the git-command error that you saw before?)

**Review by masinter — COMMENTED** [review]
is this a fix to #790? I still get NIL is not a number when I see ROOMD-INTRO but not when I See ROOMS-NOTES.

**Comment by rmkaplan** [comment]
No, that’s a completely independent problem (see my previous note):  PRETTYFILEINDEX doesn’t seem to print bitmaps correctly on textstreams, although it doesn’t fail on displaystreams (or maybe it skips printing altogether on displaystreams, I haven’t checked)

**Review by masinter — APPROVED** [review]
no more git / gh command error so take these one at a time (approving)

**Comment by masinter** [comment]
@rmkaplan I approved this a week ago, but didn't do the merge. PR#789 (rmk46) included.

**Pull request merged**
