### PR TITLE
Remove outdated FONTDESCRIPTOR fields

### PR DESCRIPTION
**Pull request by rmkaplan**
As per #1897.  I also added a DEFPRINT function for FONTDESCRIPTOR.

I'd like to get kerning to work (for fonts that have that information), but I want to confirm:  A kerning table is logically indexed by 2 characters, and it indicates how the distance between them should be modified when they appear in sequence.  I assume that most entries in such a table are 0's--no adjustment--so that a representation as a 2-level Alist in each charset would be reasonable.  Is that true?

### CODE REVIEW

**Comment by masinter** [comment]
i would wonder what fonts we have with accurate kerning information.
Without the fonts and an infrastructure to create and validate them, isn't the whole enterprise moot?
My impression is that modern current fonts use some other more flexible data structures and algorithms to manage the equivalent of kerning, with more context than just the two adjacent characters. This is, for example, the handling of characters that change shape when they occur at word endings.

**Review by masinter — CHANGES_REQUESTED** [review]
This just removes the field names. The argument is that by itself its mainly harmless because we believe those field names aren't used, and that any code that might be around that used them would be broken anyway. 

Since the goal of this is to reduce confusion for people who later try to understand the font code, a comment explaining the situation would really be helpful.

**Comment by rmkaplan** [comment]
I think changing shape (presumably character codes) at the ends of words is a different problem than changing the spacing between adjacent characters.

**Comment by rmkaplan** [comment]
I think this is ready to merge

**Review by masinter — APPROVED** [review]

**Pull request merged**
