### PR TITLE
remove .IMPTR files (byproduct of hardcopy of tedit Interlisp Manual)

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Review by nbriggs — COMMENTED** [review]
These were all explicitly added by Arun on Dec 13, 2020.  Are we *sure* they're unnecessary?

**Comment by nbriggs** [comment]
Reading the IMTEDIT.TEDIT -- I guess if we've made the TOC and INDEX then we don't need the IMPTR files, though they don't seem to be a particular problem.

**Comment by masinter** [comment]
Every time you TEdit hardcopy a file, it regenerates the .IMPTR file.
It corresponds to the page numbers which might depend on the output format (Postscript, Interpress, Press) and the fonts used for that format.

**Comment by Anzus** [comment]
Yup, they can be removed.

**Review by nbriggs — APPROVED** [review]
LGTM, then.

**Pull request merged**
