### PR TITLE
Rmk37  git ignores .sysout files

### PR DESCRIPTION
**Pull request by rmkaplan**
Previously, only specific sysouts in the loadups/ directory were ignored.  But is it ever right to upload a random sysout to git, even by accident?

### CODE REVIEW

**Comment by nbriggs** [comment]
The TEDIT-CHAT patch probably shouldn't be here.  We do have `internal/loadups/starter.sysout` checked in.  If you have a pattern in .gitignore even if you explicitly try to commit something matching it won't.  I'm not sure what it does with an attempt to commit something that has previously been committed, but now is ignored.

**Comment by rmkaplan** [comment]
In TEDIT-CHAT, I wanted to remove the reference to STREAMHINT

**Comment by rmkaplan** [comment]
... but it slipped in in the wrong commit.  I'll remove it.

**Comment by rmkaplan** [comment]
> We do have `internal/loadups/starter.sysout` checked in. If you have a pattern in .gitignore even if you explicitly try to commit something matching it won't. I'm not sure what it does with an attempt to commit something that has previously been committed, but now is ignored.

I assume that it won't delete the file, either locally or remotely.  With this in .gitignore, I'm still able to make loadups.

Much more likely that a sysout would be accidentally created and slip in to a commit, than that we want to update our starter sysout.  If we did want to do that, the .gitignore could be temporarily reverted.

**Comment by masinter** [comment]
I wonder about this. Doing a "git add" without checking for and examining new files seems like a bad practice. But all this does is let you "git add" without looking to see if you really want them.  Sure there are work-arounds but this just adds some complexity.... 
Don't git add new things without checking.

**Pull request closed without merging**
