### PR TITLE
move derived files to web site; bring over more docs and utilities from envos

### PR DESCRIPTION
**Pull request by masinter**
- move extra files and derived PDFs from repo
- add back in files to check out from envos/LISPCORE/internal/library

### CODE REVIEW

**Comment by masinter** [comment]
too many moving pieces

**Comment by rmkaplan** [comment]
Yes, I think now the master has too many changed files compared to some of the other pr branches, so it overflows the comparison code.

I think I should withdraw my rmk51, and redo it under the new origin/master.  Or wait until you have finished the rest of this documentation round, and merged.

**Comment by masinter** [comment]
I'm going to hold off on moving any more documentation files until it's clearer what's going on with the documentation. So leave rmk51.

**Comment by masinter** [comment]
with the new web site, we should check to see if this is appropriate now

**Pull request closed without merging**
