### PR TITLE
Add (FILES LAFITE) to UNIXMAIL -- must load lafite before loading UNIXMAIL

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Review by nbriggs — APPROVED** [review]
LGTM.

**Comment by rmkaplan** [comment]
In order to get UNIX mail to run, it appears that you also have to execute (LAFITEMODE ‘UNIX).  If UNIXMAIL hasn’t been loaded by then, shouldn’t that cause the file to load?

**Comment by nbriggs** [comment]
I don't think so.  You load the delivery modes you want and it updates the menu, and if there are multiple you can choose one, otherwise it uses the single one loaded.  I'd rather not have it go off trying to load a file that may or may not exist, and may or may not be a file that contains a Lafite mode definition -- why should `(LAFITEMODE 'MAILSHARE)` go and load `MAILSHARE.LCOM`?

**Comment by nbriggs** [comment]
(and the modes are not predefined, so there's no reason to know to map UNIX to UNIXMAIL)

**Pull request merged**
