### PR TITLE
Fix sysout makesys to make new versions

### PR DESCRIPTION
**Pull request by masinter**
wound up pushing into \COPYSYS. Move generic \COPYSYS into ADIR (and also VMEMSIZE) to remove MOD44IO from loadup.

### CODE REVIEW

**Review by rmkaplan — CHANGES_REQUESTED** [review]
Since the branch did not include a sysout to test, I ran scripts/loadup-all.sh to make one.  It fell into URAID:
sysout is tmp/init.dlinit
running /Users/kaplan/Local/medley3.5/git-medley/../maiko/darwin.x86_64/ldeinit -g 1042x790 -sc 1024x768 -m 256
start /Users/kaplan/Local/medley3.5/git-medley/sources/XREM.CM
Failed to find UNIXCOMM file handles; no processes

*Error* URAID Called:
Enter the URaid
IL:\MISCAPPLY*SSIONSSNSSSsions:SIONS

**Review by rmkaplan — APPROVED** [review]
With the last changes, I was able rebuild from scratch and verify that the SYSOUT is now dealing properly with versions and extensions.

**Comment by nbriggs** [comment]
Using a fresh pull from this branch, it fails for me with "CHECKTRAN+ is an undefined function" compiling LLTIMER, new fns definition for \SETUPTIMERmacrofn, ...

**Comment by nbriggs** [comment]
Screen Shot 2021-03-21 at 11 30 27 PM

**Pull request merged**
