### PR TITLE
Move net and unused sources

### PR DESCRIPTION
**Pull request by masinter**
This PR moves or deletes duplicate or unused files to two folders: obsolete and net.
Deleted were files that were duplicate or are now newly generated.
The RDSYS file is now generated as part of MAKEINIT.
The directory structures under net and obsolete match their original location.

This PR goes a long way toward fixing #226

### CODE REVIEW

**Review by nbriggs — COMMENTED** [review]
Can you arrange for it to make all new files for a loadup NOT in place -- that is, in tmp or subdirectories of tmp?   Having it dirty the git tree before you have a chance to test the result is likely to cause errors.

**Comment by masinter** [comment]
That was one of my objectives -- RDSYS and I-NEW and the init sysouts and dribble files are now all built in tmp. The only things I wasn't sure of was where to put the .dribble files.
tmp is in .gitignore

**Comment by masinter** [comment]
it isn't quite feasible to .gitignore loadups, since you need a working sysout to run makeinit. I suppose putting the new lisp and full sysouts in tmp would be OK... let everyone build their own?

**Comment by nbriggs** [comment]
I wouldn't expect many people to do their own loadups.  The lisp.sysout and full.sysout should be pre-built and in the repository, but if you run the loadup scripts then it should put them in tmp and ignore them -- if you have something that should go back into the git repository as a new loadup then you manually copy it over to the right place and check it in on a new branch, along with the Lisp files you changed that required the new loadup, file a PR, and explain what's going on.

**Review by nbriggs — COMMENTED** [review]
We should have another round of changes to do a "make install" which puts a copy of the fonts in the right directory structure and with the correct case of names, and copies of the lispusers and library code, and the distributed sysouts and startup script -- everything you need to actually run medley -- into an appropriate place.   You should be able to "git clone", "cd medley", "make install", "cd ..", "rm -rf medley" and then run it.  It shouldn't depend on anything within the git directory.

**Comment by masinter** [comment]
What about using the github release mechanism to let people just install medley and maiko without any git use at all?

We're pretty close to being able to automate most of that with a couple of self-hosted runners.

**Comment by nbriggs** [comment]
Sure -- the Lisp side should be completely machine independent, no runners needed.  The maiko side can either be a binary for what we have runners for, or source with a "make/make install" which should be very easy.   We'll probably want to rework the makefiles though -- they don't need to be as messy as they are.

**Review by nbriggs — COMMENTED** [review]
Device Independent color operations -- functions for manipulating HLS and named colors.

**Review by nbriggs — COMMENTED** [review]
Why does it make sense to move, for example, `clos/3.5/boot.lisp` to `obsolete/clos/2.0/boot.lisp` and likewise with a bunch of other files where the version changed when it went to `obsolete`

**Comment by masinter** [comment]
this must have been another git funny. What I did was git mv from clos the old versions into obsolete, and then git mv the 3.5 files down.  But I didn't do a commit between the actions.

**Review by nbriggs — COMMENTED** [review]
Are the UNBOXEDOPS not the gateway to the maiko ubf[123].c code, which implements the UBFLOAT1, 2, and 3 opcodes with various alpha values for all kinds of operations.

**Comment by masinter** [comment]
I don’t remember doing anything with UNBOXEDOPS

**Comment by nbriggs** [comment]
sources/UNBOXEDOPS was deleted.

**Comment by masinter** [comment]
Duplicate of lispusers/UNBOXEDOPS

 

 

--

 <https://LarryMasinter.net> https://LarryMasinter.net  <https://interlisp.org> https://interlisp.org

**Comment by nbriggs** [comment]
It would be a lot easier to review and merge if this was separate PRs for independent changes-- as it stands, **all** of the commits need to be reviewed before **any** commits can be merged.    Duplicate lisp files seems to be independent of anything else, fonts should be a separate issue, and so on.

**Comment by masinter** [comment]
I have down doing separate commits, but the changes aren't so independent. I was using a "DuplicateFinder" which showed duplicate font files and lisp sources.  It seems error-prone to go back to master when whittling down a list of 'bad things'.
May be we can go over it #232

**Comment by nbriggs** [comment]
Separate commits doesn't help unless we're going to ignore the PR and cherry pick commits from the branch -- the PR is all or nothing.   If you keep committing to the same branch there'll never be a time when anyone can actually finish reviewing it.  It takes a lot of time to figure out from first principles whether something that you've deemed obsolete is really obsolete, or an optional feature, or duplicated by some other code (where? which package? now built in to which file? are all the dependencies really gone?)

**Comment by nbriggs** [comment]
Here's my calculated list of duplicate files in lispusers, library, sources --
```
shasum name inode
04d9aa61f890abd831c01549e4a3d6968c219711 lispusers/BLOCKS-HKB 24820622
04d9aa61f890abd831c01549e4a3d6968c219711 lispusers/H-BLOCKS.HKB 24820846
11689c7c26b14863047427987736bf1e8cbe0dce lispusers/POSTSCRIPT/PS-SEND.TEDIT 24821148
11689c7c26b14863047427987736bf1e8cbe0dce lispusers/PS-SEND.TEDIT 24821190
1ebab340ceca900f35197e2a057db6f3d18a663e lispusers/POSTSCRIPT/PS-SKETCH-PATCH.TEDIT 24821151
1ebab340ceca900f35197e2a057db6f3d18a663e lispusers/PS-SKETCH-PATCH.TEDIT 24821192
438e2865f324064873e4f7690f979a5303b994b8 lispusers/POSTSCRIPT/PS-PATCH 24821143
438e2865f324064873e4f7690f979a5303b994b8 lispusers/PS-PATCH 24821186
494578cd3573cc245489bc98ef5f4c06e33b92f2 lispusers/POSTSCRIPT/PS-RS232.TEDIT 24821146
494578cd3573cc245489bc98ef5f4c06e33b92f2 lispusers/PS-RS232.TEDIT 24821188
4e92b5aeefd0443857c91f350c114ecff44d9f1b sources/FILEIO.~7~ 24821895
4e92b5aeefd0443857c91f350c114ecff44d9f1b sources/FILEIO.~8~ 24821896
60d12ce16662deedd999986d2354e274cd2e14d5 lispusers/POSTSCRIPT/PS-TTY 24821152
60d12ce16662deedd999986d2354e274cd2e14d5 lispusers/PS-TTY 24821193
66c47439d64d083965fb507793125cb756ea69ea lispusers/LOGIC.LGC 24820960
66c47439d64d083965fb507793125cb756ea69ea lispusers/MAIN.LGC 24820997
8997c48ee909875ce8a74b516a99bfa57f41c0c3 library/TEDITFNKEYS.~2~ 24820406
8997c48ee909875ce8a74b516a99bfa57f41c0c3 library/TEDITFNKEYS.~3~ 24820407
914e428d875e0f7d2f191363dbaea98a20437cff lispusers/POSTSCRIPT/PS-TTY.TEDIT 24821153
914e428d875e0f7d2f191363dbaea98a20437cff lispusers/PS-TTY.TEDIT 24821194
98003175074d25dcb991bd90e7802ba44ad38d2a lispusers/POSTSCRIPT/PS-SKETCH-PATCH 24821149
98003175074d25dcb991bd90e7802ba44ad38d2a lispusers/PS-SKETCH-PATCH 24821191
a1d5e4347d50927216e4f36c3b6ed723ced761ea lispusers/UNBOXEDOPS.TEDIT 24821416
a1d5e4347d50927216e4f36c3b6ed723ced761ea sources/UNBOXEDOPS.TEDIT 24822257
a4bf64decfe0a9487f4243bc923fdc898c443ae0 lispusers/SIGMA20-MRR-C0.DISPLAYFONT 24821272
a4bf64decfe0a9487f4243bc923fdc898c443ae0 lispusers/SIGMA20.STRIKE 24821273
bb12c2afe79c232bffff0e2c28776947a61a7316 sources/FILEIO.LCOM.~10~ 24821882
bb12c2afe79c232bffff0e2c28776947a61a7316 sources/FILEIO.LCOM.~9~ 24821889
d61a4302e26cfe2b5830d61790ccfb5abd8bdf59 lispusers/POSTSCRIPT/PS-SEND 24821147
d61a4302e26cfe2b5830d61790ccfb5abd8bdf59 lispusers/PS-SEND 24821189
da0af0dddea6757b550a4e1a2abb9dc7f61919c5 lispusers/POSTSCRIPT/PSCFONT-FIX-FILENAME 24821155
da0af0dddea6757b550a4e1a2abb9dc7f61919c5 lispusers/PSCFONT-FIX-FILENAME 24821196
db4223ca4d11119927af6f37b5a0beb33f35ba61 lispusers/UNBOXEDOPS 24821414
db4223ca4d11119927af6f37b5a0beb33f35ba61 sources/UNBOXEDOPS 24822255
dc25559004b5b10acdf0542b3fe8fc18782a788f lispusers/POSTSCRIPT/PS-patch.tedit 24821154
dc25559004b5b10acdf0542b3fe8fc18782a788f lispusers/PS-patch.tedit 24821195
de930440f5739d3fc2843929d4f86d268164cdbf lispusers/TMAX-ENDNOTE 24821350
de930440f5739d3fc2843929d4f86d268164cdbf lispusers/TMAX-ENDNOTE.~1~ 24821353
de930440f5739d3fc2843929d4f86d268164cdbf lispusers/TMAX-ENDNOTE.~2~ 24821350
e2052cf2b789d32439a148d5e30c606657884f03 lispusers/POSTSCRIPT/PS-RS232 24821145
e2052cf2b789d32439a148d5e30c606657884f03 lispusers/PS-RS232 24821187
eea6d2d103569690a9f7ebd143146f37a82992a8 lispusers/POSTSCRIPT/POSTSCRIPTSTREAM.TEDIT 24821142
eea6d2d103569690a9f7ebd143146f37a82992a8 lispusers/POSTSCRIPTSTREAM.TEDIT 24821164
```
I believe these could be resolved independent of any other changes.  If we check that all the files in lispusers/POSTSCRIPT are duplicates of things not in the POSTSCRIPT directory, we could just delete the directory.  It shows up some oddities where we should check why MAIN.LGC and LOGIC.LGC are the same and why they might be named this way, ditto for BLOCKS-HKB and H-BLOCKS.HKB.  We should also consider whether SIGMA20-MRR-C0.DISPLAYFONT should be in the fonts directory and why it might have been released in lispusers...

**Pull request closed without merging**
