### PR TITLE
GITFNS quote branch names in git commands

### LINKED ISSUE #1691: GITFNS prc fails if pull request branch name contains parenthesis
**Describe the bug**
The `prc` command of GITFNS fails with a "Command failed: ..." error if any pull request branch name includes parens. For example, `rmk19--Shorter-directory-names-in-COMPAREDIRECTORIES-printout-(costmetic)` . 

**To Reproduce**
1. Files loaded GITFNS.LCOM
2. Type `prc` to Exec window.
3. INTERLISP-ERROR Break window opens with 
image

**Expected behavior**
Display of menu of open PRs.

**Context (please complete the following information):**
 - OS: Windows 11, WSL, Ubuntu
 - OS Version: Ubuntu 22
 - Host arch: x86_64
 - Maiko version: [e.g. commit ID from `git log | head`]
 - IL:MAKESYSDATE: 30-Apr-2024

**Additional context**
See PR #1692 for potential fix (but may conflict with PR #1689)

### PR DESCRIPTION
**Pull request by MattHeffron**
Attempt to fix #1691 
NOTE: This PR is built on top of #1689

### CODE REVIEW

**Comment by MattHeffron** [comment]
I just realized that I should have created the PR as changes to the branch from PR #1689 ([rmk18--GITFNS-with-JSON-prc](https://github.com/Interlisp/medley/tree/rmk18--GITFNS-with-JSON-prc)), instead of from master.

**Comment by masinter** [comment]
Until and unless we bulletproof all our scripts please don't use parentheses in branch names 

######I would prefer keeping to a-z 0-9 and -  but at least avoid characters that are interpreted by the shell

**Comment by nbriggs** [comment]
I agree with Larry - a branch name doesn't need to be the full documentation, a couple of hyphen separated key words should do, and the creators initials if you're trying to keep things straight.  It's almost ephemeral, but the branch name *will* show up in the merge history comment.  The branch itself is quite likely to get GC'd once the merge has been done.

My take on it is that the PR description is to guide the reviewers as to the overall expectation for what the individual commits are trying to accomplish - but it is also ephemeral.  A PR is a github construct completely outside the git repository.  The individual commits (should) say exactly what is going on, and those are maintained in any (every) git clone.

**Review by rmkaplan — APPROVED** [review]
LGTM

**Pull request merged**
