### PR TITLE
Rename migration directory

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Comment by rmkaplan** [comment]
I think it is a very bad idea to have files with copies of FILEKGRECORDS, SEDIT-DECLS, and TABLEBROWSERDELCS in this directory.  If you load it in, you may be screwed.

If this needs those records, it should load those files from library or sources.

**Comment by masinter** [comment]
@Anzus ?

**Comment by rmkaplan** [comment]
Whatever it is doing, it shouldn’t have its own version of system declarations.  It should recompile with the standard ones.

**Comment by masinter** [comment]
do this later

**Pull request closed without merging**
