### PR TITLE
Rmk96 move sketch files to library/sketch 

### PR DESCRIPTION
**Pull request by rmkaplan**
This moves library/SKETCH to library/sketch/SKETCH, and all the library/SKETCHXXX files  to library/SKETCH-XXX.

This follows the hyphen-file convention of other multi-file applications (like TEDIT, TMAX).  It means that when the sketch GETFN on SKETCH-OBJ is required, the file SKETCH and all its components will be loaded instead.

### CODE REVIEW

**Review by masinter — APPROVED** [review]
some files were just renamed without remaking fileCOMS?

Anyway, running with this shows no problem.

**Comment by rmkaplan** [comment]
I thought I got all the fileCOMS.  If I missed some, I'll fix them.  Should be consistent.

**Comment by rmkaplan** [comment]
Actually, I think the coms are correct.  I did not move the files MATMULT and SCALEBITMAP into the SKETCH subdirectory, I think SKETCH is just one of their clients, they are not part of SKETCH.

**Comment by rmkaplan** [comment]
But the file SKETCHOPS should not have been carried along.  It is deleted in PR #1464

**Pull request merged**
