### PR TITLE
Rmk62 old tedit formats and nits

### PR DESCRIPTION
**Pull request by rmkaplan**
Mainly reading old-format TEDIT files.  A few other minor adjustments

### CODE REVIEW

**Comment by nbriggs** [comment]
Loaded up a new sysout on this branch, tried to TEDIT `obsolete/sunloadup/HOWTO-MAKE-SYSOUT.TEDIT` and it failed with `ARG NOT TEXTOBJ - NIL` from within `TEDIT.GET.OBJECT` -- should be easy to reproduce this problem.

**Review by masinter — COMMENTED** [review]
in TEDIT-FILE's \TEDIT.CONVERT.FOREIGN.FORMAT doesn't the call to (OPENTEXTSTREAM "") now treat "" as a pathname?

**Comment by rmkaplan** [comment]
New commits address Larry's earlier comment about (OPENTEXTSTREAM "").  Unrelated to the other problem in loading image objects.

**Comment by masinter** [comment]
(HCFILES) runs on all TEDIT / SKETCH files in Medley repo.
LGTM

**Review by masinter — APPROVED** [review]

**Pull request merged**
