### PR TITLE
Replace chat via "rlogin" with chat via "ssh"

### PR DESCRIPTION
**Pull request by nbriggs**
Modern systems are unlikely to be configured with "rlogin" access,
remote login, if available, is likely to be via "ssh", so use that.

### CODE REVIEW

**Comment by nbriggs** [comment]
Closes #511

**Comment by rmkaplan** [comment]
UNIXMAIL is in library.  Why isn’t it in library/lafite with the other lafite stuff.  Is it independent of Lafite?

**Review by rmkaplan — APPROVED** [review]
There is now an extra space in the RPAQ? diffs, I wonder why.

Otherwise, LGTM

**Comment by nbriggs** [comment]
> There is now an extra space in the RPAQ? diffs, I wonder why.

The prettyprinting seems to have added font-change characters around the variable names which were not previously present, and added a space after them before the closing ")" -- don't know why.

> UNIXMAIL is in library.  Why isn’t it in library/lafite with the other lafite stuff.  Is it independent of Lafite?

Unrelated to this change, I think?

**Pull request merged**
