### PR TITLE
change for CapsLock & Shift to be XOR vs OR.

### PR DESCRIPTION
**Pull request by MattHeffron**
This addresses issue #1486.
It adds a SHIFTXORLOCK in addition to SHIFTORLOCK.
Because this is low-level, it should be tested significantly!

### CODE REVIEW

**Comment by nbriggs** [comment]
I can't tell if this is an unconditional change from the old to the new behavior, or if it is selectable, and if it's selectable... how?

**Comment by MattHeffron** [comment]
This is an unconditional change, as is.
Making it conditional should be pretty straightforward.

**Comment by MattHeffron** [comment]
Many of the changes seen in the diff are due to PRETTYPRINT changes since previous LLKEY version (Aug-2021).

**Comment by rmkaplan** [comment]
Yes, that’s what the GITFNS commands are trying to deal with.

**Review by masinter — APPROVED** [review]
lgtm

**Pull request merged**
