### PR TITLE
SEDIT-MAN  arms Meta-D in SEDIT for man page as per #1623

### PR DESCRIPTION
**Pull request by rmkaplan**
Marked as draft because  SEDIT:ADD-COMMAND doesn't quite work as documented.  In particular, it doesn't automatically put in both upper and lower case versions, even though all other commands are specified as case-insensitive.

So the work-around here adds 2 menu items instead of one.  

This issue would go away, if/when this is built into SEDIT-COMMANDS.  But that would create a dependency on DINFO being present.  So, another MOVD? ?

(Meta,I ) (for Info) would have been a better mnemonic, but that's taken for the Inspect command.)

(Separate issue:  SEDIT:GET-SELECTION causes an error if there is no selection, rather than returning SELTYPE NIL as documented.  NLSETQ suppresses that--CLIPBOARD probably also needs an NLSETQ)

### CODE REVIEW

**Comment by masinter** [comment]
you didn't like the idea of multiple meta-H bringing in more documentation?
Or meta-?

**Comment by nbriggs** [comment]
I don't like the idea of a modal interface and having to count how many meta-H have been done without changing the selection and reseting the count if you change the selection or issue any other command.

**Comment by rmkaplan** [comment]
I didn’t think about key alternatives, just worked through the Sedit issues.  I think recognizing multiple keypresses would be hard.  I like meta-?.

**Comment by nbriggs** [comment]
Entering meta,? will mean you have to type meta-shift-/ and that's not a particularly convenient key combination.

**Comment by nbriggs** [comment]
and by the way, meta,/ is taken for extract so if you make a mistake typing meta,? you'll make a mess.

**Comment by rmkaplan** [comment]
So, stick with meta-D ?

**Comment by pamoroso** [comment]
To get `?` on my [Italian keyboard](https://journal.paoloamoroso.com/in-praise-of-cheap-keyboards) I press `Shift-'`. While pressing `Meta-?` (aka `Meta-Shift-'`) at an Exec flashes the screen in Medley Online, SEdit seems to recognize it as it warns `Unknown command: Meta-?`.

However, `Meta-D` would be more straightforward.

**Comment by nbriggs** [comment]
I would (stick with meta,[Dd]) - though I'd think about whether it should be case-insensitive or whether meta,d and meta,D should do two related functions, say, meta-d does man and meta-D does cl:describe

**Comment by pamoroso** [comment]
Good point, I actually meant the `D` key without regard for a specific case and either or both would be fine with me.

**Comment by masinter** [comment]
My concern is that there are several kinds of documentation available unevenly. People say Interlisp is a "Lisp2" but it is really a "lisp N" where every filepkgtype is a (different or overlapping) namespace.

If the symbol is defined with a "definer" (FUNCTIONS with DEFUN or DEFMACRO, VARIABLES with DEFPARAMETER DEFCONSTANT .. ) then there might be a documentation string. Not all functions have one and FNS and VARS ..?
If the symbol is in CAR of form or in a `#'` FUNCTION context there are TWO argument lists, an 'actual' and one with extended syntax. And the possibility of showing the correlation to the argument list.
For things that are defined in the repo (WHEREIS ..T) and there's a TEDIT file that mentions it (FFILEPOS) .
And, finally, there is the possibility of showing the CLHS page.  

we could show all that are available at the same time... thats what HELPSYS does currently. In some cases its too much.

**Comment by rmkaplan** [comment]
I don’t think there should be a lot of different keystrokes to distinguish a lot of different kinds of information that may or may not be available.  This is an interface to get information, it shouldn’t require the user to already have a lot of information in order to make use of it.

Right now I made it call the GENERIC.MAN.LOOKUP that the man command calls.  This often pops up a menu to select different types (although it isn’t exactly clear why the menu often has what appear to be duplicate items, sometimes with asterisks.  Mentions of the same thing in different places?).

We could have perhaps a different implementation function pop up a different kind of menu to let the user choose what source or what kind of display they want to see.  Or, as it does now with this generic function, let it rip.

**Review by masinter — APPROVED** [review]
let it out for others to experiment with, even though the design isn't settled.

**Comment by rmkaplan** [comment]
Note:  this isn’t (yet) part of the loadup, to play with it you have to LOAD(SEDIT-MAN.LCOM).

**Comment by pamoroso** [comment]
When I load SEDIT-MAN.LCOM on Medley Online and open SEdit (e.g. `(ED 'MYFUN '(FNS :DONTWAIT))`) the program hangs, i.e. pressing any key or clicking any mouse button on the SEdit window has no effect. The rest of the Medley session is responsive as usual though.

**Comment by pamoroso** [comment]
I experimented a bit more with SEDIT-MAN.LCOM and it seems only middle-clicking has no effect.

**Comment by pamoroso** [comment]
Never mind, middle-clicking seems to be working again with SEdit when SEDIT-MAN.LCOM is loaded.

**Pull request merged**
