### PR TITLE
More consistent HCFILES filenames

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Comment by pamoroso** [comment]
I don't know if it's related to these changes but I get a 404 error when visiting https://interlisp.org/src

**Comment by masinter** [comment]
interlisp.org/src should be live again with the "new" URLs. I was working on trying to simplify the process of building it.

**Comment by pamoroso** [comment]
I confirm https://interlisp.org/src is back online.

**Comment by masinter** [comment]
with this PR, the substring "/src/" isn't in the calls to HCFILES and MAKE-INDEX-HTMLS.
setting it up to be /src/ or /hc/ and/or   https://releases.interlisp.org  a network file server will also work'

**Review by MattHeffron — APPROVED** [review]
Approved in 7/8/24 meeting.

**Pull request merged**
