### PR TITLE
Add OPEN-URL as an available call to open a URL in a browser

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Comment by lellaninc** [comment]
Already added this functionality in the LIBRARY file UNIXUTILS.  The function is ShellBrowse(URL).

I am not wild about the ShellBrowse name, but I was just following the convention in the UNIX* library files - e.g., ShellCommand.

I am ok with renaming ShellBrowse (and its associated functions) to something else - like OPEN-URL.

**Comment by lellaninc** [comment]
See PR#1051

**Comment by fghalasz** [comment]
(Resending comment under my login rather than lellaninc)

Already added this functionality in the LIBRARY file UNIXUTILS. The function is ShellBrowse(URL).  See PR#1051

I am not wild about the ShellBrowse name, but I was just following the convention in the UNIX* library files - e.g., ShellCommand.

I am ok with renaming ShellBrowse (and its associated functions) to something else - like OPEN-URL.

**Comment by masinter** [comment]
I wanted to use OPEN-URL in the demos ... ShellBrowse camel-case is harder to type and emphasizes (too much) that it was done in the "Shell". But I'll move OPEN-URL to a new file DEMO-SETUP. Closing this PR.

**Pull request closed without merging**
