### PR TITLE
Uploaded Xerox Common Lisp Implementation Notes book in chunks

### PR DESCRIPTION
**Pull request by johnwcowan**

### CODE REVIEW

**Comment by masinter** [comment]
I'm not sure where this document belongs, and we haven't been consistent, but the documentation available as pdf's seem to be on the web site and perhaps also in the zotero bibliography,

**Comment by johnwcowan** [comment]
I think that everything should be in Medley/docs that is needed to use
Medley as it stands today.  It's parallel (physically and semantically) to
the ReleaseNotes, which gives you the Medley additions to the IRM.

**Comment by masinter** [comment]
[https://interlisp.org/docs/cl-impl-notes.pdf](https://interlisp.org/docs/cl-impl-notes.pdf) as one file, 
with link from [medley wiki](https://github.com/interlisp/medley/wiki).
There's also an HTML export at [https://interlisp.org/docs/cl-impl-notes.html](https://interlisp.org/docs/cl-impl-notes.html), but I'm not sure how usable that is.

**Comment by masinter** [comment]
As confirmed 7/18/21

**Pull request closed without merging**
