### PR TITLE
Rmk107  Rename lafite files according to hyphen conventions #1509

### PR DESCRIPTION
**Pull request by rmkaplan**
All files in library/lafite/ now begin with LAFITE-.

### CODE REVIEW

**Comment by nbriggs** [comment]
It says there are conflicts on library/lafite/UNIXMAIL (and UNIXMAIL.DFASL).  It's claiming that the LCOMs weren't renamed, but the old ones were deleted and the new ones added, and that LAFITETEDIT wasn't renamed LAFITE-TEDIT, and a few other things.  Have a look at the file changes list it sent out, where anything that is "A" and "D" should really be "R".

**Comment by rmkaplan** [comment]
I don’t understand what happened.  There were 2 commits, the first one was after doing git mv’s to rename all the files to hyphenated versions (including LCOMS and TEDIT).  After that there were no non-hyphen files left in the directory (according to ls).

I then copied updated versions (fileCOMS etc) of those files from my working directory, which did not contain any of the unhyphenated files.  And did the second commit.

So maybe git mv was not the right command? How did the original files come back?

(Separately, the goal of this is to preserve history.  But I don’t think there is much git history with these files.  Since uploading to git, has anything been done here besides the few changes that I made to update for Tedit and external-format stuff?)

**Comment by nbriggs** [comment]
The conflict with UNIXMAIL is because Larry updated UNIXMAIL to load LAFITE after you branched from master (or you hadn't updated your master branch before you created the new branch)

Your branch also seems to include Larry's "Make macros that expand to fetch or replace note the record fields used." commit to MSANALYZE.

There is one missed change to a file name, LAFITE-TIMEDDELETE still has a `(FILESLOAD LAFITEFIND)`

I looked at the commits, and I don't know why github is reporting the changes in the way it is - they seem correct.

**Comment by rmkaplan** [comment]
I’m pretty sure I started with a master that already had the UNIXMAIL update, although I had done the renaming in my working directory before that.  I was careful to put Larry’s change separately into the renamed version that I copied over.

The “Make macros” had already been merged before I created the renaming branch, that shouldn’t be an issue.

**Review by nbriggs — COMMENTED** [review]
No, adding it back to delete it is not the right answer.  It needs to be resolved with command line git, since they're binary files as far as git is concerned.

The point your branch started from on master was
```
commit 2647d98f8f21e59b05318733a039b18d07c577ec (tag: medley-240205-2647d98f)
Merge: 39ee2ecb b52015e7
Author: Frank Halasz <frank@halasz.org>
Date:   Mon Feb 5 15:12:13 2024 -0800

    Merge pull request #1519 from Interlisp/fgh_modernize-for-nc
    
    In MODERNIZE, fixed \MODERNIZED.TEDIT.BUTTONEVENTFN so it can work with Notecards
```
Let me see if I can work this one by hand.

**Comment by nbriggs** [comment]
LAFITE-HAX and LAFITE-PRIVATEDL didn't get compiled and included?
LAFITE-PRIVATEDL will compile but won't load because ADDRESSPARSERRDTBL is unbound.  Not sure where that is supposed to come from, it's not in any current LAFITE file (or anywhere else I can find) - it might be SMTP related?

**Comment by rmkaplan** [comment]
That’s the way they were, I just renamed them to carry them along.

**Comment by rmkaplan** [comment]
BTW, LAFITEPRIVATEDL was written by N.H. Briggs in 1987.

**Pull request closed without merging**
