### PR TITLE
import an LOOP macro

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Comment by pamoroso** [comment]
On Medley Online, when I load CML-LOOP.DFASL I get this break window with the error `Can't find package for DEFINE-FILE-INFO reader environment XLP`:

cml-loop-error

Not sure I'm loading it correctly.

**Comment by masinter** [comment]
Tbh I don’t know how to set up the package declaration so it works with makefile.--LarryMasinter.netOn Mar 14, 2024, at 9:19 AM, Paolo Amoroso ***@***.***> wrote:﻿
On Medley Online, when I load CML-LOOP.DFASL I get this break window with the error Can't find package for DEFINE-FILE-INFO reader environment XLP:
cml-loop-error.png (view on web)
Not sure I'm loading it correctly.

**Comment by masinter** [comment]
I changed the file name to XCL-LOOP and added it to the loadup.
I fixed the package problems I hope.

**Comment by pamoroso** [comment]
Now it seems to be working. Pretty cool.

xcl-loop

**Comment by nbriggs** [comment]
Why XCL- instead of CML?

Should loop be in its own package or should it be part of cl:/lisp: package if it's part of the language spec (or xcl: if it's "our own" implementation)

**Comment by MattHeffron** [comment]
I concur with @nbriggs . 
Why is this in the "XLP" package? Doesn't that mean that all of the symbols that the `loop` macro uses for its _extended_ form would have to be imported into whatever package the code using it is read in? Or all used as **xlp::_symbol_**?
In fact, the `loop` macro **_itself_** is in the "XLP" package and it isn't even exported from that package. So, even to use the simplest loop form requires either: 
**(xlp::loop _forms_)** 
or to **(import (find-symbol "loop" "xlp") "_name of package of code using loop_")** before the code using the `loop` macro is read, 
or to put a similar import as part of the DEFPACKAGE of the file environment of a file using the macro.

If it's part of the standard, then put it into the correct package.

Is the point not to redefine the existing `loop` macro as defined in CMLSPECIALFORMS? It looks like _that_ implementation and syntax would be handled correctly by the new _fuller_ `loop` macro.

**Comment by masinter** [comment]
Interestingly the other words in the extended f  op rm are pname only and can be in any or no (I interned at all. Only two symbols are exported: loop and loop-finish. That's why it works without the contortions @MattHeffron predicted. Try it!

**Review by pamoroso — APPROVED** [review]
The latest version seems to be working fine and no special handling of packages is required. Here's a quick test of evaluating at a XCL Exec a few `loop` expressions from Peter Seibel's book:

xcl-loop

Running an infinite loop with `(loop)` works too.

**Comment by pamoroso** [comment]
A call to this implementation of `loop` to iterate over a hash table produces the error `Undefined car of form XLP::WITH-HASH-TABLE-ITERATOR` as [reported](https://github.com/Interlisp/medley/issues/609#issuecomment-2002053775) in issue #609.

**Comment by nbriggs** [comment]
Both `WITH-HASH-TABLE-ITERATOR` and `WITH-PACKAGE-ITERATOR` definitions seem to be missing. (Latest version of the branch moves the package for the internal mechanism of the `loop` macro to LOOP: and sorts out the conflict with CMLSPECIALFORMS which already defined LOOP)

**Comment by nbriggs** [comment]
The author of the `loop.lisp` has the hash table bits as well.

**Comment by masinter** [comment]
I changed the package to "LOOP" and made sure "LOOP" and "LOOP-FINISH" were exported from the LISP package.

**Comment by masinter** [comment]
i spent the better part of a day on Both WITH-HASH-TABLE-ITERATOR and WITH-PACKAGE-ITERATOR and have decided to put that on ice because I don't want to change Medley's implementation of hash-tables or packages.
Those two features aren't part of LOOP.
I did find a couple of differences/bug fixes with a newer loop.liap.

**Comment by masinter** [comment]
I missed the parts about -TABLE-ITERATOR and WITH-PACKAGE-ITERATOR being used in some LOOP iterators.
But I don't want to hold this for them. I made a separate issue.

**Pull request merged**
