### PR TITLE
Add environment variables move medley files to /home/medley.

### PR DESCRIPTION
**Pull request by stumbo**
Add Build_Date, Maiko_Release and Medley_Release environment variables.

Touches on issue #499

### CODE REVIEW

**Review by masinter — APPROVED** [review]
LGTM, thank you

**Comment by nbriggs** [comment]
See the red circle at the end?  That says "missing newline at end-of-file", so it shouldn't look good.

Screen Shot 2021-12-14 at 11 18 05 PM

**Comment by masinter** [comment]
? is that a problem? it was missing before this update

**Comment by nbriggs** [comment]
It's definitely something to avoid.  It's absolutely something to fix if you're already editing the file.  Not *all* utilities that read files treat EOF the same as EOL with respect to processing the last line in the file.  That's why it's flagged in red, and shows up with `\ missing newline at end-of-file` any time you run a (git) diff.

**Pull request merged**
