### PR TITLE
Move lispusers>BACKGROUND*.PRESS to obsolete>lispusers>

### PR DESCRIPTION
**Pull request by rmkaplan**
Cleanup lispusers.  I don't think we can now do anything with press files

### CODE REVIEW

**Comment by masinter** [comment]
not true -- those files are used by the BACKGROUND lispusers to pull out screen background images.
READPRESS I think is the function.

**Comment by rmkaplan** [comment]
Would it be better, then, to pull them out once and just save the bitmaps?

**Comment by masinter** [comment]
There are more .press files in the PARC archives. 
e.g.
eris/lispcore/demo/CINDY.PRESS         eris/lispcore/demo/SCRIPT.PRESS
eris/lispcore/demo/DIPLOMACYMAP.PRESS  eris/lispcore/demo/STEINHEIM.PRESS
eris/lispcore/demo/JO.PRESS            eris/lispcore/demo/TIFFANY.PRESS
eris/lispcore/demo/NETWORKIMAGE.PRESS  eris/lispcore/demo/TWODOLLAR.PRESS

**Comment by nbriggs** [comment]
Yes, READPRESS is the function.  Please don't get rid of these.

**Pull request closed without merging**
