### PR TITLE
Fixes and cleanup in HISTMENU, CLIPBOARD, and MANAGER

### PR DESCRIPTION
**Pull request by MattHeffron**
Update HISTMENU with Exec target check & cleanup
Add to CLIPBOARD support for M-x (Extract) in SEdit 
Fix the file "See" commands in MANAGER

### CODE REVIEW

**Review by rmkaplan — CHANGES_REQUESTED** [review]
Arming meta-X (or meta-x) as "extract" in SEDIT conflicts with the existing behavior wherein meta-x means "expand"--substitute the code for a given function in place of the call.

It would be nice if we could synchronize the meta-keys in Tedit and Sedit with what we now see in modern interfaces, but we have to figure out where to move the existing bindings.

I added meta-X in Tedit (and also meta-z (undo), meta-a (all), and meta-g (find again)) because they did not conflict.  I held off on Sedit, because we have to decide where to move the current meta-x behavior.  Similarly, Sedit meta-a means abort, not all, and meta-z means mutate, not undo.  meta-g is safe, I just haven't gotten around to it.

But we have to make a decision about how to shift the other key bindings.  Meanwhile, and unhappily, I think this should be saved for later.

**Comment by masinter** [comment]
https://github.com/Interlisp/medley/issues/58 Want consistent keybindings (as part of Modernize)

I had started a table of key bindings https://drive.google.com/file/d/1jFxxEkZW3yKY5m7Bp8pjzkWeF3CYevp2/view
but I'm having trouble opening it.

**Comment by fghalasz** [comment]
@rmkaplan  > I added meta-X in Tedit (and also meta-z (undo), meta-a (all), and meta-g (find again)) because they did not conflict.

Adding meta-x, meta-z etc to to TEdit is modernizing it only if you consider the MacOS modern.  For the vast majority of the modern world (i.e., Windows users and - to some extent - Linux users) the modernized bindings should be ctrl-x, ctrl-z, etc.

**Comment by rmkaplan** [comment]
There may be a different set of conflicts in the Windows world then in the Mac, but still some issues.  ctrl-X “extract" also conflicts with the Sedit “exit”, for example.

Would we do any better if we tried to map Tedit and Sedit onto emacs key bindings, and piggy-back on however conflicts have been resolved there?

**Comment by nbriggs** [comment]
> Would we do any better if we tried to map Tedit and Sedit onto emacs key bindings, and piggy-back on however conflicts have been resolved there?

No.   For example, in emacs (in text mode) to copy a region:  move to a point, ctrl-space to set mark, move to another point, esc-w to copy to mark-to-point region to kill-ring, move to another point, esc-w to paste.
In emacs in window mode with mouse integration (on a mac) you can use meta-x, meta-c, meta-v; or you can switch to "CUA mode" and use ctrl-x, ctrl-c, ctrl-v for cut/copy/paste-- and then it gets a little weird, because if you have some text selected ctrl-x copies it, but if there is no text selected then ctrl-x is a command prefix (and ctrl-x, ctrl-c is still exit... as long as you don't have text selected).   Yuk.

In Linux shells, it's ctrl-shift-x/ctrl-shift-c/ctrl-shift-v but in other apps it's usually ctrl-x/ etc.

**Comment by masinter** [comment]
Issue #58 is the "consistent keybindings" issue. I'll start another chart of existing keybindings (with and without 'modernize') against different Lisp SEdit TEdit and TTYIN editing.

In the meanwhile, the function belongs where this PR puts it. I'd rather see it bound to some keystroke rather than unbound. If there was an easy option to move 'expand' from 'meta-X' to 'control-meta-X' and usurp meta-X for this function, I'd put that in my init until we have a more general solution.

**Comment by masinter** [comment]
See Discussion https://github.com/Interlisp/medley/discussions/637 on bundling different edits into one PR or not.

**Comment by MattHeffron** [comment]
I created a new Pull Request that excludes the changes to Clipboard due to the issues of conflicting key bindings.

**Pull request closed without merging**
