### PR TITLE
misc lispusers changes -- UNIXYCD, lsee

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Review by rmkaplan — COMMENTED** [review]
Seems reasonable to get it out of the loadup files.  But is there a better home for something like this, in one of the source files, rather than a separate little addon file?

**Comment by masinter** [comment]
just didn't belong in the loadup, and there wasn't any other place that came to mind.
The other bit left over is FIXMETA, which seems odd.

Maybe UNIXCOMM?  
I'd like to move ShellCommand renamed to UNIX-COMMAND or something.
GITFN has GIT-COMMAND which isn't quite right.
I could see 'cd' use the project list so I could do 'cd loops/truckin' ? not sure though.

Now that we're getting more users.... 

addresses some but not all of #257 move things in LOADUP-FULL to where they ~should~ go.

**Comment by rmkaplan** [comment]
You can say cd {GLOOPS}/truckin or {WLOOPS}/truckin, i.e. using the pseudohosts that the medley-project defines.  You can also use the cdg and cdw commands, to specify the project without the brackets:  cdw loops trucking, cdg loops truckin.

Maybe there should also be a generic pseudohost LOOPS that is a synonym for GLOOPS, for people that don’t make that git/working distinction, or that gets set up instead when the directory in the GIT-MAKE-PROJECT doesn’t have “git-xxx” or “working-xxx” in the spec.

It is a little awkward, notationally, that this all goes through the host field of a file name, so you need the { }, instead of a pseudo-directory that gets popped off into the pseudo host.  Maybe it could be done instead by fiddling with unpackfilename and packfilename, when a directory doesn’t exist (check to see if a prefix is known as a pseudo directory).

**Comment by masinter** [comment]
will redo this

**Review by rmkaplan — APPROVED** [review]

**Pull request merged**
