### PR TITLE
Use -NF (no fork) on ldinit during loadup

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Review by nbriggs — APPROVED** [review]
LGTM.  The `echo sysout "$1"` duplicates the info you'll get when it echoes `running: ...` with the sysout name.

**Comment by rmkaplan** [comment]
I believe I just clicked merge

**Comment by rmkaplan** [comment]
But after downloading and trying, I still see that message.

**Comment by nbriggs** [comment]
Worked for me:
```
--------------
sysout tmp/init.dlinit
running: ldeinit  -g 1042x790 -sc 1024x768 -m 256  -NF tmp/init.dlinit
greet: /Users/briggs/Projects/medley/sources/XREM.CM
MAKEINIT.EXPRESSIONSSNSSSsions:SIONS
---- made ----
-rw-r--r--  1 briggs  staff  4973568 Jul 20 12:21 tmp/init-mid.sysout
--------------
```
You don't have your own copy of run-medley somewhere else on your path do you?

**Comment by nbriggs** [comment]
For the merges, choose "squash and merge" rather than "merge" -- it should default to the last one you used.

**Comment by nbriggs** [comment]
The garbled MAKEINIT message is because something is writing CR instead of LF when it puts out:
```
sysout tmp/init.dlinit
running: ldeinit  -g 1042x790 -sc 1024x768 -m 256  -NF tmp/init.dlinit
greet: /Users/briggs/Projects/medley/sources/XREM.CM
evaluating initial expressions:
PACKAGE-CONVERSION-TABLE.EXPRESSIONS
LLSUBRS.EXPRESSIONS
FILEIO.EXPRESSIONS
EXTERNALFORMAT.EXPRESSIONS
IMAGEIO.EXPRESSIONS
LLBASIC.EXPRESSIONS
LLGC.EXPRESSIONS
LLARRAYELT.EXPRESSIONS
LLINTERP.EXPRESSIONS
LLMVS.EXPRESSIONS
DEFSTRUCT-RUN-TIME.EXPRESSIONS
CMLSEQBASICS.EXPRESSIONS
LLARITH.EXPRESSIONS
LLFLOAT.EXPRESSIONS
LLBIGNUM.EXPRESSIONS
LLREAD.EXPRESSIONS
XCCS.EXPRESSIONS
LLCHAR.EXPRESSIONS
LLDATATYPE.EXPRESSIONS
IOCHAR.EXPRESSIONS
LLKEY.EXPRESSIONS
LLTIMER.EXPRESSIONS
DTDECLARE.EXPRESSIONS
ATBL.EXPRESSIONS
LLCODE.EXPRESSIONS
COREIO.EXPRESSIONS
AOFD.EXPRESSIONS
ADIR.EXPRESSIONS
PMAP.EXPRESSIONS
VANILLADISK.EXPRESSIONS
ATERM.EXPRESSIONS
APRINT.EXPRESSIONS
ABASIC.EXPRESSIONS
AERROR.EXPRESSIONS
AINTERRUPT.EXPRESSIONS
MISC.EXPRESSIONS
BOOTSTRAP.EXPRESSIONS
CMLMACROS.EXPRESSIONS
CMLEVAL.EXPRESSIONS
CMLPROGV.EXPRESSIONS
CMLSPECIALFORMS.EXPRESSIONS
LLRESTART.EXPRESSIONS
LLERROR.EXPRESSIONS
LLSYMBOL.EXPRESSIONS
LLPACKAGE.EXPRESSIONS
PACKAGE-STARTUP.EXPRESSIONS
CONDITION-PACKAGE.EXPRESSIONS
XCL-PACKAGE.EXPRESSIONS
PROC.EXPRESSIONS
evaluating initial expressions:
CMLARRAY.EXPRESSIONS
DSK.EXPRESSIONS
UFS.EXPRESSIONS
PASSWORDS.EXPRESSIONS
FONT.EXPRESSIONS
LLDISPLAY.EXPRESSIONS
APUTDQ.EXPRESSIONS
COMPATIBILITY.EXPRESSIONS
DMISC.EXPRESSIONS
CMLLIST.EXPRESSIONS
CMLCHARACTER.EXPRESSIONS
CMLREADTABLE.EXPRESSIONS
MAIKOBITBLT.EXPRESSIONS
MAIKOINIT.EXPRESSIONS
MAKEINIT.EXPRESSIONS

---- made ----
-rw-r--r--  1 briggs  staff  4973568 Jul 20 12:31 tmp/init-mid.sysout
--------------
```

**Pull request merged**
