### PR TITLE
*** Update scripts and utilities to use renamed directories

### PR DESCRIPTION
**Pull request by masinter**
updates FINDFILE-WITH-EXTENSIONS (when called on a root name FOO or FOO-something) to look at FOO>FOO-something.extension) to handle subdirs,

### CODE REVIEW

**Comment by rmkaplan** [comment]
Perhaps a separate issue, but if we organize multi-file library or lispusers packages with their own subdirectory (a good idea), what is the FILES argument to EDITCALLERS or FINDCALLERS that will sweep through and find everything?  (FILDIR '*.;) sweeps just the top level.

**Comment by masinter** [comment]
I split this into separate PRs to facilitate review

**Comment by masinter** [comment]
this was spllit into separate PRs but has a correction to the release-medley script ("medley/docs/doctools" => "medley/doctools"

**Comment by masinter** [comment]
will include in a separate PR

**Pull request closed without merging**
