### PR TITLE
Medley logow

### PR DESCRIPTION
**Pull request by masinter**
New Medley Interlisp logow (using old KOTOLOGOW); reenable LOGOW in Loadup

### CODE REVIEW

**Comment by masinter** [comment]
this isn't working, but I think it isn't needed for release

**Comment by masinter** [comment]
The problem was the FILEPKG bug... now ready for review again.
Changes LOGOW to use Medley as the name in a KOTOLOGW look.
Further refinements of LOGOW still pending (include release tag?)

**Review by rmkaplan — COMMENTED** [review]
The new LOGOW seems to have a lot of stuff under (if NIL...)
Is that intended?

**Comment by masinter** [comment]
I wanted to comment it out but just meta-; in sedit leaves it illegible. I suppose I should have left a comment.

**Comment by rmkaplan** [comment]
In that situation, I revert to (* …)

**Review by rmkaplan — COMMENTED** [review]
LOGOW has both a DFASL and an LCOM.  Doesn't have FUNCTIONS or DEFMACROS, LCOM should be OK

**Comment by masinter** [comment]
got rid of DFASL and venue logo code

**Review by rmkaplan — APPROVED** [review]
Looks good.  I take it that the way to programmatically close the window is (AND LOGOW (CLOSEW LOGOW))

I think FILEPKG is the same file as in a separate PR, but that's OK

**Pull request merged**
