### PR TITLE
loadup failure ldeinit

### PR DESCRIPTION
**Pull request by masinter**
replacement for #276

### CODE REVIEW

**Comment by nbriggs** [comment]
You don't need to make a new PR when you need to make changes to the branch that the PR references -- if the code isn't correct you just fix it and push it back to the same branch.  The PR is just a separate thing (in github) that says "hey, look at this branch" and provides convenience buttons for disposition.

**Review by nbriggs — CHANGES_REQUESTED** [review]
This has the same issues as before.  Please don't use `which`, use `command -v ...` instead.  There's a typo at line 1 of scripts/loadup-init.sh.

**Comment by nbriggs** [comment]
Would you prefer I fix it and repush the branch?

**Comment by nbriggs** [comment]
If you want me to fix it, you can leave the branch there and I'll just update it.  No need to delete the branch or the PR -- that's just making more work.

**Comment by masinter** [comment]
please
[history.txt](https://github.com/Interlisp/medley/files/6174211/history.txt)

**Pull request closed without merging**
