### PR TITLE
Rmk57  mostly gitfns improvements, other minor cleanups

### PR DESCRIPTION
**Pull request by rmkaplan**

### CODE REVIEW

**Comment by nbriggs** [comment]
If "gh" isn't installed, something like "prc xxxx" can end up in an infinite loop.

**Comment by nbriggs** [comment]
Perhaps #830 could be addressed here since you're modifying COMPAREDIRECTORIES anyway.

**Comment by rmkaplan** [comment]
I haven’t encountered that.  Do you see it now?

Maybe it was just a bad compile.

**Comment by rmkaplan** [comment]
How can I tell if gh is installed?  Just try the command and see if it fails?

**Comment by nbriggs** [comment]
Just made a fresh full.sysout on this branch --
```
% git status
On branch rmk57--Mostly-GITFNS-improvements,-other-minor-cleanups
Your branch is up to date with 'origin/rmk57--Mostly-GITFNS-improvements,-other-minor-cleanups'.
```
and the first thing I did with it was (FILESLOAD GITFNS), which produced
Screen Shot 2022-07-17 at 10 14 59 AM

I notice that in the source it puts out

```
(DECLARE%: EVAL@COMPILE

(RECORD CDVALUE ((CDDIR1 CDDIR2 CDCOMPAREDATE CDSELECT CDMAXNC1 CDMAXNC2) . CDENTRIES)
                (RECORD CDVALUE (CDPARAMETERS))
                CDMAXNC1 _ (CREATE CDMAXNCHARS)
                CDMAXNC2 _ (CREATE CDMAXNCHARS))

(RECORD CDENTRY (MATCHNAME INFO1 DATEREL INFO2 . EQUIV))

(RECORD CDINFO (FULLNAME DATE LENGTH AUTHOR TYPE EOL))

(RECORD CDMAXNCHARS (NCFULLNAME NCLENGTH NCAUTHOR NCTYPE NCDIR))
)
```
so isn't it going to try to use CDMAXNCHARS for CDMAXNC1 (and 2) before it defines the CDMAXNCHARS record?

**Comment by nbriggs** [comment]
> How can I tell if gh is installed? Just try the command and see if it fails?
> 
That's one way, I suppose.   Otherwise I'd let the command to use be set up by the site profile (e.g., (SETQ *GH-COMMAND* "/usr/local/bin/gh") and if it's NIL don't try to do gh related things.

**Comment by nbriggs** [comment]
doing "command -v gh" should return 0 status code if it is present, 1 status code if it is not.

**Comment by rmkaplan** [comment]
Now addressed in this branch. Please test again.

**Review by nbriggs — COMMENTED** [review]
I've verified that it fixes my two complaints, about the record order and the looping when "gh" is not installed.

**Comment by masinter** [comment]
I don't think loading GITFNS should initialize the projects -- the projects might be different every time you start lisp. Make an (GIT-INIT) which initializes the projects / verifies them and call it when first doing a git command or call, and after a return from LOGOUT, SYSOUT or MAKESYS. Maybe the convention of erasing

**Comment by nbriggs** [comment]
Closes #830

**Comment by nbriggs** [comment]
It's misinterpreting the branch names --

Screen Shot 2022-07-17 at 1 13 26 PM

```
% git branch  
  fix-run-medley-inferred-medleydir
  master
  rmk32
  rmk42--ADIR-has-new-UNPACKFILENAME.STRING
* rmk57--Mostly-GITFNS-improvements,-other-minor-cleanups
```
and the git branch -r is
```
  origin/HEAD -> origin/master
  origin/TEDIT2-Move-TEDIT-files-to-separate-tedit-subdirectory--attempt-2
  origin/TEDIT3-Refactor-TEDIT.BUILD.PCTB
  origin/add-newer-library-envos
  origin/add-nfs-docs
  origin/clos-in-library
  origin/compile-uncompiled
  origin/fgh002
  origin/fgh003
  origin/fgh004
  origin/fgh005
  origin/fix-run-medley-inferred-medleydir
  origin/fix-scanfilehelp
  origin/git-release
  origin/hcfiles-patches
  origin/lispusers-cleanup
  origin/lmm10
  origin/loadup-db3
  origin/loadup-fix
  origin/loadup-fixes
  origin/masinter-patch-README
  origin/master
  origin/more-unsafe
  origin/move-lispusers-lists
  origin/move-logic
  origin/restore-version-dates
  origin/rmk29
  origin/rmk30
  origin/rmk31
  origin/rmk32
  origin/rmk33
  origin/rmk34
  origin/rmk35
  origin/rmk36
  origin/rmk37
  origin/rmk38
  origin/rmk40--Shakedown-GITFNS-projects
  origin/rmk41--TEDIT-interprets-strings-as-filename
  origin/rmk42--ADIR-has-new-UNPACKFILENAME.STRING
  origin/rmk43--Move-lispusers-spline-and-c150-fonts-to-subdirectories
  origin/rmk44--Lispusers-to-obsolete
  origin/rmk45--TESTUPF-to-internal,-TEDIT-pathnames,-minor-doc-changes
  origin/rmk46
  origin/rmk47
  origin/rmk51-End-game-of-external-format-integration
  origin/rmk52-Fix-format-for-error-stream
  origin/rmk53-Added-SYSTEM-EXTERNALFORMAT
  origin/rmk54--refactor-versions-of-DSPCREATE
  origin/rmk55--GITFNS-with-redirect
  origin/rmk56--FILEPOS-with-external-formats-#3
  origin/rmk57--Mostly-GITFNS-improvements,-other-minor-cleanups
  origin/rmk58--centralize-reading/writing-of-strike-fonts
  origin/tedit-rename-glitch
  origin/update-manager
```

**Review by masinter — APPROVED** [review]
not sure how things got twisted.
master had better MEDLEY-UTILS, SKETCH files marked `<`. 
I pulled those in from master 
`git checkout master -- internal/MEDLEY-UTILS*` etc and now lgtm

**Comment by rmkaplan** [comment]
OK, I see it.  It was happening for me too, just scrolling away before I saw it in the exec window. 

I think the records were in the wrong order.

(Not sure whether these records are needed at runtime, but I won’t finagle that now)

**Comment by rmkaplan** [comment]
Is the problem the origin/HEAD -> origin/master ?  Should I do some sort of coercion in that case?

**Comment by rmkaplan** [comment]
I haven’t been thinking that you would carry a sysout from one environment to another and expect it to migrate to new projects in a new location.  

The idea was to encapsulate some of the project properties (like the exclusions and the commonly accessed directories), and to make it easy to start up if projects are in a reasonable location wrt MEDLEYDIR or other shell variables.

I suppose it could be set up that the canonical properties are stored in a separate list, and let the make-project just instantiate the locations and the pseudohosts.  

It could also be that the get-project at the top of every command implicitly does the make-project if there isn’t yet a project associated with the name, but in that scenario it would only know how to find the directories in canonical places.

I’m not sure what the target functionality should be.

**Comment by nbriggs** [comment]
> Is the problem the origin/HEAD -> origin/master ? Should I do some sort of coercion in that case?
> […](#)

It was confused by the text `origin/HEAD -> origin/master` which it was attempting to interpret as a literal branch name... this is git saying that `origin/HEAD` is a symbolic name that points to `origin/master`, so they're equivalent and it provides two branch names that one could expect to reference.

**Comment by masinter** [comment]
I've been switching back and forth between Cygwin and WSL and Online with various configurations.
The pathnames are all different and I often want to SAVEVM on one and start that lisp.virtualmem on another.

**Pull request merged**
