### PR TITLE
release more

### PR DESCRIPTION
**Pull request by masinter**
- move badfiles
- fix release to include sources

### CODE REVIEW

**Comment by masinter** [comment]
i meant to make the change to the release script separate, but the other change (adding MAKE-PS to internal/library) got added.

It's ready to go

**Comment by masinter** [comment]
unfortunately this PR includes two different changes:
1. fixes to the release process to eliminate errors on GREET
2. initial inclusion (in internal/lilbrary) of a 'MAKE-PS' package to convert all TEdit files in a given directory to postscript

**Comment by masinter** [comment]
will fix #446

**Comment by nbriggs** [comment]
I'll be on this in the AM.

**Review by nbriggs — APPROVED** [review]
This looks OK.  I'd note, though, that you can't run the release-medley.sh on macOS as tar there doesn't support --exclude-backups.  If we need it to run on macOS (in the case that github desktop is installed) then --exclude-backups is equivalent to excluding ".#*", "*~", and "#*#"

**Comment by nbriggs** [comment]
There's a spelling error for release in the release notes -- and the description of "the medley release is here..." seems to be attempting to use backquotes in odd ways and failing to get the desired result.

**Pull request merged**
