### PR TITLE
WIP: improve hcfiles using directory apply

### PR DESCRIPTION
**Pull request by masinter**

### CODE REVIEW

**Comment by rmkaplan** [comment]
Here are a few comments after taking an initial look at this:

The NTH and ASSOC in MAKE-WHEREIS-LOOPS should be replaced by (GIT-GET-PROJECT 'LOOPS 'CLONEPATH).

I don't think that MAPFILES should be a special function here that defaults its base to MEDLEYDIR. We should provide a more general facility in DIRECTORY, perhaps just by adding a functional argument to the existing FILDIR that coerces the COLLECT into an apply.  Then MEDLEYDIR would be passed here as the default argument to the generic.

But then, I would prefer to see the default argument passed as (PSEUDOFILENAME (MEDLEYDIR)).  This would effectively simulate commonlisp's notion of a "logical pathname" (albeit currently without accepting path structures--a separate issue), would tend to make the file references portable to other environments.

**Comment by rmkaplan** [comment]
Also, did you intend to switch from LCOM to DFASL ?

**Comment by masinter** [comment]
I'm restarting with this PR -- will close others.

**Comment by masinter** [comment]
subsumed

**Pull request closed without merging**
