### PR TITLE
TEDITSCREEN, TEDITHCPY: Remove absolute NS charcodes

### PR DESCRIPTION
**Pull request by rmkaplan**
Also eliminated \MAIKO.DISPLAYLINE.  Git got twisted up between branches, stuck in <<<< in some files, I think I unscrambled it.  (Had to copy TEDIT again separately).  Still says TEDITHCPY.LCOM is conflicted, even though I have completely TCOMPLed it.  Git sucks.

### CODE REVIEW

**Comment by rmkaplan** [comment]
Git screwed me, but I think/hope I straightened it out.

**Comment by masinter** [comment]
This PR doesn't look right -- it deletes TEDITHCPY
sometimes it's easier to save your work, start over from master
and pull in the changes you want to make

**Comment by masinter** [comment]
the problem was another PR https://github.com/Interlisp/medley/commit/5e6eb4b4247bd60cf7f94770dc679351713ce557

that got merged in had also modified TEDITHCPY

**Comment by rmkaplan** [comment]
Yes, I tried 15 ways of getting around that.  I think the issue was that the previous PR hadn’t been merged or included, things got out of step, and recovery is hard.

**Review by masinter — CHANGES_REQUESTED** [review]
A newer TEDITHCPY was pushed to 'master' since the one this one started with.
That's the conflict. I think the only way to deal with this is to start with that one.
you can `git checkout master -- library/TEDITHCPY ` to pull a single file from another branch.

**Comment by rmkaplan** [comment]
I'm not sure what changes you are requesting.  Git is screwed up, but I think these files are good.  Do I have to redo this edit to get synchronized?

**Comment by nbriggs** [comment]
This is what `git whatchanged` says about your commit:
```
commit 3cef1afdbc869e5539dd2cbff63feecf463e9325
Author: rmkaplan <ron.kaplan@post.harvard.edu>
Date:   Tue Sep 21 16:34:16 2021 -0700

    TEDITSCREEN, TEDITHCPY: Remove absolute NS charcodes
    
    Also eliminated \MAIKO.DISPLAYLINE.  Git got twisted up between branches,
    stuck in <<<< in some files, I think I unscrambled it.  (Had to copy TEDIT
    again separately).  Still says TEDITHCPY.LCOM is conflicted,
    even though I have completely TCOMPLed it.  Git sucks.

:100644 100644 4805d48... 13e8edf... M  library/TEDITDCL
:100644 100644 a4dd4df... da6d0c8... M  library/TEDITDCL.LCOM
:100644 000000 1e187a4... 0000000... D  library/TEDITHCPY
:100644 100644 ad68331... 437dc5f... M  library/TEDITHCPY.LCOM
:100644 100644 58d3080... 772d983... M  library/TEDITSCREEN
:100644 100644 9e18859... 55c7580... M  library/TEDITSCREEN.LCOM

```
So it says that it's going to delete the source TEDITHCPY -- which for sure isn't what we want.
The last change to TEDITHCPY was in your commit 5e6eb4b4247bd60cf7f94770dc679351713ce557:

```
Author: rmkaplan <ron.kaplan@post.harvard.edu>
Date:   Mon Sep 20 11:17:55 2021 -0700

    HARDCOPY, TEDITHCPY:  fix #491
    
    INITVAR for PRINTFILETYPES, fix the coms for the Interpress option in TEDITHCPY
    
    (This branch is accumulating little TEDIT glitches)

:100644 100644 75206ae... 1e187a4... M  library/TEDITHCPY
:100644 100644 e19a426... ad68331... M  library/TEDITHCPY.LCOM
:100644 100644 9d9c790... 145f90b... M  sources/HARDCOPY
:100644 100644 423b38b... 27e0ec8... M  sources/HARDCOPY.LCOM

```
So it looks as though you'd need to get your last updated TEDITHCPY from master, remake the changes that you made for this last change, redo the save and compile, then add a commit of just TEDITHCPY and TEDITHCPY.LCOM to this branch and push it. But, before that,  e-mail me the output of `git status` so I have a better understanding of the state of things...

**Comment by rmkaplan** [comment]
I copied my currently-edited file to some other name, then did the checkout from master, tne copied my file back to its original name.  Before doing the commit, here is the status

[Ronalds-MacBook-Pro:~/Local/medley3.5/git-medley] kaplan% git status
On branch TEDIT-Remove-absolute-character-numbers
Your branch is up to date with 'origin/TEDIT-Remove-absolute-character-numbers'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   library/TEDITHCPY

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   library/TEDITHCPY
	modified:   library/TEDITHCPY.LCOM

**Comment by nbriggs** [comment]
I'm not sure how it is in a state where it thinks that library/TEDITHCPY is both a "new file" and "modified".
It would have been illuminating to know the "git status" before you changed anything.

If your copy of TEDITHCPY includes the changes that you had made that are already on master (TEDIT.HARDCOPYFN and the TEDITHCPYCOMS) then I think you can "git add library/TEDITHCPY library/TEDITHCPY.LCOM" and then "git commit" and "git push"

Then I'll take a look at what the state of the branch is on github.

-- Nick

**Comment by rmkaplan** [comment]
As noted, before, git generally doesn’t’ interact well with the Medley work style.

I almost always interact with git thru the git desktop instead of individual commands.  At this pont, the desktop shows


For my understanding, if I were to commit and push this situation in the desktop, would it have the same effect as the sequence of individual commands?

**Comment by nbriggs** [comment]
The image is missing from the last comment.   I don't use the github desktop, so I don't know what it might be doing differently, if anything, from using the command line.

But... if you commit and push we've not lost anything, and the only thing that can get into a sub-optimal state is the branch you're currently working on (assuming it doesn't get prematurely merged into master).

**Comment by rmkaplan** [comment]
I did the push from inside the desktop.  I think it should be clean now.

**Comment by rmkaplan** [comment]
Can you do COMPARESOURCES when files are on different branches, so you can see what’s meaningful?

**Comment by nbriggs** [comment]
You can extract the file from one branch (using git show) and then compare it to the current file (presumably on a different branch).

I'll do that and show you how and what the results were...

**Comment by nbriggs** [comment]
So the easy thing to do is:
```
% git fetch          # make sure we've got locally everything on origin (github)
% git status
On branch TEDIT-Remove-absolute-character-numbers
Your branch is up-to-date with 'origin/TEDIT-Remove-absolute-character-numbers'.
% cp library/TEDITHCPY /tmp/TEDITHCPY-NEW
% git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
%
```
Then in Medley I did 
```
(CL:WITH-OPEN-STREAM (D (OPENSTREAM "{dsk}/tmp/tedithcpy-diffs" 'OUTPUT 'NEW)) (COMPARESOURCES (FINDFILE "TEDITHCPY") "{unix}/tmp/TEDITHCPY-NEW" NIL NIL D]
```
which produced in /tmp/tedithcpy-diffs:
```
Comparing {UNIX}<tmp>TEDITHCPY-MASTER. dated 26-Sep-2021 12:24:16 and {UNIX}<tmp>TEDITHCPY-NEW. dated 
26-Sep-2021 12:26:06:

---Functions: 
TEDIT.HARDCOPYFN: 
SAME


---Vars:

TEDITHCPYCOMS: 
(-5- (COMS -2-       (P (LET ((IPVALUES (ASSOC & (ASSOC (QUOTE INTERPRESS) &)))) (COND (IPVALUES & (LISTPUT
 IPVALUES & (FUNCTION \TEDIT.HARDCOPY)))))) (P &)) (COMS & (VARS (TEDIT.DONT.BREAK.CHARS (QUOTE (8482 8483
 8491 8492 8508 8525 8539 8537 8535 9249 9251 9253 9255 9257 9283 9315 9317 9319 9326 9505 9507 9509 9511
 9513 9539 9571 9573 9575 9582))) (TEDIT.DONT.LAST.CHARS (QUOTE (8524 8538 8536 8534)))) (GLOBALVARS TEDIT.DONT.BREAK.CHARS --)
) &)
(-5- (COMS -2- (P &) (P (LET ((PRESSVALUES (ASSOC & (ASSOC (QUOTE PRESS) &)))) (COND (PRESSVALUES & (LISTPUT
 PRESSVALUES & (FUNCTION \TEDIT.PRESS.HARDCOPY))))))) (COMS & (INITVARS (TEDIT.DONT.BREAK.CHARS (CHARCODE
 ("41,42" "41,43" "41,53" "41,54" "41,74" "41,115" "41,133" "41,131" "41,127" "Hira,41" "Hira,43" "Hira,45"
 "Hira,47" "Hira,51" "Hira,103" "Hira,143" "Hira,145" "Hira,147" "Hira,156" "Kata,41" "Kata,43" "Kata,45"
 "Kata,47" "Kata,51" "Kata,103" "Kata,143" "Kata,145" "Kata,147" "Kata,156"))) (TEDIT.DONT.LAST.CHARS 
(CHARCODE ("41,114" "41,132" "41,130" "41,126"))))) &)


TEDIT.DONT.BREAK.CHARS: 
QUOTE -> CHARCODE, 8482 -> "41,42", 8483 -> "41,43", 8491 -> "41,53", 8492 -> "41,54", 8508 -> "41,74"
, 8525 -> "41,115", 8539 -> "41,133", 8537 -> "41,131", 8535 -> "41,127", 9249 -> "Hira,41", 9251 -> "Hira,43"
, 9253 -> "Hira,45", 9255 -> "Hira,47", 9257 -> "Hira,51", 9283 -> "Hira,103", 9315 -> "Hira,143", 9317 -> "Hira,145"
, 9319 -> "Hira,147", 9326 -> "Hira,156", 9505 -> "Kata,41", 9507 -> "Kata,43", 9509 -> "Kata,45", 9511 -> "Kata,47"
, 9513 -> "Kata,51", 9539 -> "Kata,103", 9571 -> "Kata,143", 9573 -> "Kata,145", 9575 -> "Kata,147", 9582 -> "Kata,156"

TEDIT.DONT.LAST.CHARS: 
QUOTE -> CHARCODE, 8524 -> "41,114", 8538 -> "41,132", 8536 -> "41,130", 8534 -> "41,126"


---Expressions:
(              (LET ((IPVALUES (ASSOC & (ASSOC (QUOTE INTERPRESS) &)))) (COND (IPVALUES & (LISTPUT IPVALUES
 & (FUNCTION \TEDIT.HARDCOPY))))) (LET & --))
((LISTPUT & --)(LET ((PRESSVALUES (ASSOC & (ASSOC (QUOTE PRESS) &)))) (COND (PRESSVALUES & (LISTPUT PRESSVALUES
 & (FUNCTION \TEDIT.PRESS.HARDCOPY))))))


------(DECLARE: EVAL@COMPILE DONTCOPY --) forms------

---Expressions:
These are not on {UNIX}<tmp>TEDITHCPY-NEW.:
(GLOBALVARS TEDIT.DONT.BREAK.CHARS TEDIT.DONT.LAST.CHARS)
```
I find the diffs for the expressions hard to interpret, but looking at your newer version of the file, you don't have the conditional for the presence of INTERPRESS before adding \TEDIT.HARDCOPY.

**Comment by nbriggs** [comment]
Another way to deal with doing COMPARESOURCES is the way I do it for maiko -- I always have a git clone on the master branch in a different directory name that I can compare my current branch changes to (in my case, with regular diff).  I just have to remember to "git pull" in there before comparing.

**Comment by rmkaplan** [comment]
I have no idea how that got lost, and now I have no idea what the target state is supposed to be, or how to get there.

I’ll try to figure it out.  But then I think I will try to work mostly outside of git, update from time to time.  It isn’t worth it.

**Comment by nbriggs** [comment]
The requested changes are OK, we're back to having a TEDITHCPY, which, while it is missing the change to avoid installing the hardcopy function when INTERPRESS is not loaded, is otherwise OK to merge.

**Review by nbriggs — APPROVED** [review]
LGTM now.

**Review by masinter — APPROVED** [review]

**Pull request merged**
